### ISSUE TITLE
port settings

### ISSUE THREAD

**Issue by billmoling** [mattermost/mattermost-docker#102]
I am following the steps to set up the application. I am hosting the docker on Microsoft Azure. And after I set up the Endpoint. I connect to the mattermost, but it shows the 502 bad gateway from "nginx/1.4.6 (Ubuntu)".
I also check some document about change the Nginx configuration in sites-available. is it necessary? if so, could you please guide the process?

The default web port is 80, and the default app port is also 80. Is it correct? I saw some document set the app port should be 8065?

I try to use docker-compose up without -d to see the error when I access the web container.

Error as below:
2017/02/22 09:28:58 [error] 11#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 27.115.44.67, server: , request: "GET / HTTP/1.1", upstream: "http://172.17.0.7:80/", host: "139.219.237.83:58060"

**Comment by xcompass** [comment]
I don't think you need to change the sites-available. Yes, default port is 80 for nginx, which is a reverse proxy for mattermost app. MM app container doesn't expose any port to the host. the web and app containers are connected through docker network. 

Could you post the full log of `docker-compose up`? Ideally, if you could remove the previous generated files with `rm -rf volumes` (you shouldn't have any data there since it failed to start. But if there is any, make sure you backup your data).

**Comment by billmoling** [comment]
I change the yml file to map 8060:80 for tcp. and then I map the endpoint on Azure 58060 to 8060.

the log like below :

db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
mattermostdocker_db_1 exited with code 1
web_1  | 27.115.44.67 - - [23/Feb/2017:07:47:48 +0000] "GET / HTTP/1.1" 502 583 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
web_1  | 2017/02/23 07:47:48 [error] 11#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 27.115.44.67, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:80/", host: "jenkinsdps.chinacloudapp.cn:58060"
web_1  | 27.115.44.67 - - [23/Feb/2017:07:47:50 +0000] "GET /favicon.ico HTTP/1.1" 502 583 "http://jenkinsdps.chinacloudapp.cn:58060/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
web_1  | 2017/02/23 07:47:50 [error] 11#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 27.115.44.67, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:80/favicon.ico", host: "jenkinsdps.chinacloudapp.cn:58060", referrer: "http://jenkinsdps.chinacloudapp.cn:58060/"

**Comment by xcompass** [comment]
It looks like there are some permission issues with database directory. Have you run docker-compose with a different user before? Could you run `ls -lha volumes/db/var/lib/postgresql/data` to check the ownership of the db directory? If the user is different from what you are currently login, you may have to change the file ownership or remove the directory completely.

**Comment by billmoling** [comment]
[devops@jenkinsdps mattermost-docker]$ ls -lha volumes/db/var/lib/postgresql/data
total 8.0K
drwxr-xr-x. 2 root root 4.0K Feb 23 07:44 .
drwxr-xr-x. 3 root root 4.0K Feb 23 07:44 ..
[devops@jenkinsdps mattermost-docker]$ 
---------------------
Does it relate to the command I run by sudo? could you show me how to change the file ownership?

**Comment by xcompass** [comment]
Yes. Looks like your current user is devops and the owner of the directory is root. So looks like you have run it before with root (possibly by sudo). If you want to run as devops user (which may not have enough permission to use port 80 on the host), you can run the following command `chown -R devops:devops volumes`. This will change the ownership to devops for all files and directories under volumes. Then you can try to run docker-compose. 

If you still get some permission issues, you may want to run docker-compose with root.

**Comment by billmoling** [comment]
I would like to take a try. But I did run every command with Sudo, otherwise the command would say that it can't connect to docker Deamon. I will have a try by Chown, then update back. 
Thanks




On Fri, Feb 24, 2017 at 8:23 AM +0800, "Pan Luo" <notifications@github.com> wrote:












Yes. Looks like your current user is devops and the owner of the directory is root. So looks like you have run it before with root (possibly by sudo). If you want to run as devops user (which may not have enough permission to use port 80 on the host), you can run the following command chown -R devops:devops volumes. This will change the ownership to devops for all files and directories under volumes. Then you can try to run docker-compose.


If you still get some permission issues, you may want to run docker-compose with root.

**Comment by xcompass** [comment]
If your docker is complaining about the permission when you run it with devops user, then you probably have to run docker-compose with root or use sudo.

**Comment by billmoling** [comment]
I run docker-compose build, up-d all with "sudo" at the very beginning, so do you thing the privilege is still a problem?

**Comment by xcompass** [comment]
if you run everything with sudo, it should be fine.

**Comment by billmoling** [comment]
but all these issue/error message are the result running with sudo...

**Comment by xcompass** [comment]
Could you try to remove the volumes directory completely and run with root user? e.g. `su -` and then docker-compose up?

**Comment by billmoling** [comment]
I am confused,  I run all the command with sudo, it should be ok for the volumes privilege with root.

**Comment by xcompass** [comment]
It should. But privilege to run postgres is dropped from root to postgres inside db container. So postgres won't be able to create the files. My suggestion is just shot in the dark. Not sure why the postgres data is created by root but if you remove it, the container may create the directory with appropriate ownership and permission. Another idea is to change the ownership manually. e.g. `chown -R 999:999 volumes/db/var/lib/postgresql` and run docker-compose up again.

**Comment by billmoling** [comment]
after run the command , the result is like below. But the error still exists


[devops@jenkinsdps mattermost-docker]$ ls -lha volumes/db/var/lib/postgresql/data
total 8.0K
drwxr-xr-x. 2 systemd-bus-proxy ssh_keys 4.0K Feb 24 03:23 .
drwxr-xr-x. 3 systemd-bus-proxy ssh_keys 4.0K Feb 24 03:23 ..
[devops@jenkinsdps mattermost-docker]$

**Comment by xcompass** [comment]
So you still see error like `db_1 | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied`. Weird. Could you post the full log again? In case there are some clue.

**Comment by billmoling** [comment]
Please check the full logs

web_1  | Starting Nginx
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
web_1  | ln: failed to create symbolic link '/etc/nginx/sites-enabled/mattermost': File exists
app_1  | Configure database connection...cp: cannot create regular file '/mattermost/config/config.json': Permission denied
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
app_1  | sed: can't read /mattermost/config/config.json: No such file or directory
app_1  | sed: can't read /mattermost/config/config.json: No such file or directory
app_1  | sed: can't read /mattermost/config/config.json: No such file or directory
app_1  | sed: can't read /mattermost/config/config.json: No such file or directory
app_1  | OK
app_1  | Wait until database db:5432 is ready...
app_1  | sed: can't read /mattermost/config/config.json: No such file or directory
mattermostdocker_db_1 exited with code 1
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
..........
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chown: cannot read directory ‘/var/lib/postgresql/data’: Permission denied
.........

**Comment by billmoling** [comment]
any insight?

**Comment by xcompass** [comment]
What's your docker-compose version?

**Comment by billmoling** [comment]
docker-compose version 1.11.1, build 7c5d5e4

**Comment by billmoling** [comment]
any update?

**Comment by xcompass** [comment]
It seems like there still permission issue. Are you able to run docker-compose on you local environment. Not sure if there is anything special on Azure. Never played with it.

**Comment by apocalypsebg** [comment]
I encountered the same problem today. And couldn't get it running, Now it's working (yay!)
Using commit a034f8f7ab9b52d65ff20cd4b5da10893b385d70 on master. 

I'm running on a VPS instance, all root install. 
Here's the info on the system:

```bash
Virtualization: microsoft
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-514.16.1.el7.x86_64
Architecture: x86-64


Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64


docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

```

What I've changed is:

```patch
     build:
       context: app
       # comment out for team edition
-      dockerfile: Dockerfile-enterprise
+      #dockerfile: Dockerfile-enterprise
     restart: unless-stopped
     volumes:
-      - ./volumes/app/mattermost/config:/mattermost/config:rw
-      - ./volumes/app/mattermost/data:/mattermost/data:rw
-      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
+      - ./volumes/app/mattermost/config:/mattermost/config:Z
+      - ./volumes/app/mattermost/data:/mattermost/data:Z
+      - ./volumes/app/mattermost/logs:/mattermost/logs:Z
       - /etc/localtime:/etc/localtime:ro


     build: db
     restart: unless-stopped
     volumes:
-      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
+      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data:z
       - /etc/localtime:/etc/localtime:ro

```

**Comment by billmoling** [comment]
apocalypsebg's solution fix my issue. It seems a difference between CentOS and ubantu

**Comment by xcompass** [comment]
Thanks for the update.
