### ISSUE TITLE
Database errors (relation X does not exist) on clean installation/startup

### ISSUE THREAD

**Issue by futuretec** [mattermost/mattermost-docker#105]
Hey there,

I'm a first time user of Mattermost and just tried to use the mattermost-docker package to bootstrap a demo installation.
Unfortunately I can't proceed with the setup, since there are database errors on the initial startup.

This issue seems to be pretty common, since there are a lot of similar reported issues on this topic. Also see the currently open GitHub issue [101](https://github.com/mattermost/mattermost-docker/issues/101)

As I said this is a clean installation/fresh docker-compose start within the following environment:
- Ubuntu 16.04 LTS
- docker v1.13.0 (49bf474)
- docker-compose v1.9.0 (2585387)

Any thoughts or fixes?

> 
db_1   | ERROR:  relation "systems" does not exist at character 19
db_1   | STATEMENT:  SELECT Value FROM Systems WHERE Name='Version'
db_1   | ERROR:  relation "idx_teams_name" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teams_description" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teams_invite_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teams_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teams_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teams_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teammembers_team_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teammembers_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_teammembers_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_team_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_name" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channelmembers_channel_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channelmembers_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_channels_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_channel_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_root_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_message_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_posts_hashtags_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_email" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_all_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_all_no_full_name_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_names_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_users_names_no_full_name_txt" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_audits_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_sessions_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_sessions_token" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_sessions_expires_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_sessions_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_sessions_last_activity_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_oauthapps_creator_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_oauthaccessdata_client_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_oauthaccessdata_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_oauthaccessdata_refresh_token" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_oauthauthdata_client_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_incoming_webhook_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_incoming_webhook_team_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_outgoing_webhook_team_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_incoming_webhook_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_incoming_webhook_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_incoming_webhook_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_outgoing_webhook_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_outgoing_webhook_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_outgoing_webhook_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_command_team_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_command_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_command_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_command_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_preferences_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_preferences_category" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_preferences_name" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_password_recovery_code" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_emoji_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_emoji_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_emoji_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_status_user_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_status_status" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_fileinfo_update_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_fileinfo_create_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_fileinfo_delete_at" does not exist
db_1   | STATEMENT:  SELECT $1::regclass
db_1   | ERROR:  relation "idx_reactions_post_id" does not exist
db_1   | STATEMENT:  SELECT $1::regclass

**Comment by xcompass** [comment]
It seems those errors are related to mattermost itself. But you can safely ignore them. Mattermost works fine. If you still want to troubleshoot, you can post it here: https://www.mattermost.org/troubleshoot/

**Comment by xcompass** [comment]
I'll close this issue for now. Let me know if you still have any question.
