### ISSUE TITLE
cross-origin websocket errors due to nginx reverse proxy

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-docker#107]
Similar to https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1966
in which the error 

[2017/02/11 15:39:49 UTC] [EROR] websocket connect err: websocket: origin not allowed
[2017/02/11 15:39:49 UTC] [EROR] /api/v3/users/websocket:connect code=500 rid=x6foapujtprsufxri8fyxucjie uid=nnqmxgkn5tbxjg98yhq5y664ze ip=5.51.59.153, 192.168.0.4 Failed to upgrade websocket connection [details: ]

is logged - there appears to errors relating to the prevention of cross-origin as a result of incomplete nginx configuration

If you are to look at the example on https://docs.mattermost.com/install/install-ubuntu-1604.html or any other page which includes an nginx reverse proxy there's a section -

location /api/v3/users/websocket {
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
client_max_body_size 50M;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Frame-Options SAMEORIGIN;
proxy_buffers 256 16k;
proxy_buffer_size 16k;
proxy_read_timeout 600s;
proxy_pass http://backend;
}

in addition to the the / location definition

as a result this project will give errors

[EROR] websocket connect err: websocket: origin not allowed

on the backend and

WebSocket connection to 'wss:///api/v3/users/websocket' failed: Error during WebSocket handshake: Unexpected response code: 403

from the browser. this is displayed as

"Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port." in a blue banner.

in line with the current config I would imagine this should be added to

https://github.com/mattermost/mattermost-docker/blob/master/web/mattermost and https://github.com/mattermost/mattermost-docker/blob/master/web/mattermost-ssl

with this modification -

location /api/v3/users/websocket {
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
client_max_body_size 50M;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Frame-Options SAMEORIGIN;
proxy_buffers 256 16k;
proxy_buffer_size 16k;
proxy_read_timeout 600s;
proxy_pass http://app:80;
}

however having made that change myself and restarting the 'web' container the errors persist. I'm unsure of the cause for this.

**Comment by alecisec** [comment]
Issue can be closed

Was a result of uncommenting this section - 

# server {
#     listen         80;
#     server_name    mattermost.example.com;
#     return         301 https://$server_name$request_uri;
# }

**Comment by alecisec** [comment]
I suspect this may be as a result of changing the "Site URL" setting in mattermost but have not been able to confirm

**Comment by RangerRick** [comment]
I'm seeing the same thing with Mattermost 3.7.3 behind an NGINX 1.9.3 (Ubuntu LTS 14) proxy.

**Comment by coronin** [comment]
I am seeing a lot of this error with mattermost 3.8.2 behind nginx with nginx config as in the 16.04 LTS installation instruction.

**Comment by xcompass** [comment]
@alecisec did you find the issue? Are you still having trouble now?

**Comment by RangerRick** [comment]
FWIW, starting over using a clean NGINX config and the latest mattermost "how to set up a proxy" documentation works for me without websocket issues anymore.  (with 3.9.0)

**Comment by xcompass** [comment]
Thanks for the update!

**Comment by alecisec** [comment]
I believe my problem ended up being one of our in-line proxies, bypassing it and connecting directly to the MM server resolved the issue.

**Comment by xcompass** [comment]
Thanks for the update!

**Comment by loleg** [comment]
The [nginx proxy documentation](https://docs.mattermost.com/install/install-ubuntu-1604.html#installing-nginx-server) for Ubuntu 16 helped me out on this one. Thanks for the tip!
