### ISSUE TITLE
Alpine variant?

### ISSUE THREAD

**Issue by ptman** [mattermost/mattermost-docker#109]
Ubuntu 14.04 based image is a bit old and heavy. Since mattermost is a go project, it should be able to compile it using CGO_ENABLED=0 and get a totally static binary (`ldd $binary` gives "not a dynamic executable"). And it could be based on alpine, which is very slim compared to ubuntu. Any plans to do that?

**Comment by cjkoenig** [comment]
Hi @ptman, regarding alpine based images, I updated the alpine branch recently and created PR #92. Right now, I do not know the status and if its ever get commited (travis is OK). However, feel free to try it :-)

**Comment by tejasbubane** [comment]
Can we upgrade only `nginx` and `postgres` containers to alpine, until we test the app container for other issues?

**Comment by ptman** [comment]
I've had good success with nginx:alpine and postgres:alpine

**Comment by giabao** [comment]
@ptman 
> I've had good success with nginx:alpine and postgres:alpine
Could you share the code

**Comment by pichouk** [comment]
@ptman If you have something working, I invite you to submit PR :smile:

**Comment by cybershambles** [comment]
This looks fine for me.. but it's also been a few months

I'll test and confirm these PRs and hopefully assist with the merge

**Comment by cybershambles** [comment]
We do need to consider existing instances and plan an upgrade path

unless it's `docker-compose down; docker-compose rm; docker-compose build; docker-complose up -d`

**Comment by pichouk** [comment]
@cybershambles There is on opened PR https://github.com/mattermost/mattermost-docker/pull/135
But this change needs to be perform step by step, with some tests. The PR is stuck for now because I was not able to update my existing database with an Alpine-based one.

**Comment by pichouk** [comment]
As #208 is merged, we are now using Alpine based image :)
