### ISSUE TITLE
This server does not allow open signups

### ISSUE THREAD

**Issue by ankush981** [mattermost/mattermost-docker#111]
I got the error `This server does not allow open signups. Please speak with your Administrator to receive an invitation` when trying to create a user by sending a POST request to `/users/create` using the system admin bearer token in the header. Is this the expected response when `EnableOpenServer` is set to `false`? I find it odd, because the system admin should be able to do anything. Or perhaps I'm doing it wrong?

**Comment by xcompass** [comment]
Could you check if the "Enable Account Creation" set to false? https://docs.mattermost.com/administration/config-settings.html#enable-account-creation

**Comment by ankush981** [comment]
No, it's set to true.

**Comment by xcompass** [comment]
I guess this is expected behaviour. https://docs.mattermost.com/administration/config-settings.html#enable-open-server

If you still need more info or help, you can try https://github.com/mattermost/platform. People there are more qualified than me to answer this kind of question.

**Comment by ankush981** [comment]
Okay, thank you!
