### ISSUE TITLE
Help update to version 3.7.0

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#112]
Hi @xcompass 

Wonder if I can ask your help to update the mattermost-docker repo to version 3.7.0 please?

Thanks :)

**Comment by jasonblais** [comment]
Hey @xcompass, FYI, we just cut 3.7.1 to fix an issue ahead of tomorrow's release. 

When you update the repo, please update it to v3.7.1?

[The download links and hashes are available here](https://pre-release.mattermost.com/core/pl/zfgk8oa7kjrufr4gofpagoqtse) if needed.

**Comment by xcompass** [comment]
Both 3.6.3 and 3.7.1 are updated and tagged.
