### ISSUE TITLE
mattermostdocker_app connecting to wrong database server

### ISSUE THREAD

**Issue by aatangulov** [mattermost/mattermost-docker#113]
If linux box with mattermost docker production install Team edition have search domains in /etc/resolv.conf and some of this domains have 'db.domain' record, then 'mattermostdocker_app' will try to connect to this host 'db.domain' port 5432.
volumes/app/mattermost/logs/mattermost.log (172.16.100.100 is linux box ip):
[2017/03/16 17:02:46 +07] [INFO] Loaded system translations for 'en' from '/mattermost/i18n/en.json'
[2017/03/16 17:02:46 +07] [INFO] Current version is 3.7.0 (3.7.1/Wed Mar 15 21:26:22 UTC 2017/91d430b2a39a03b052cc103f73f44c68cbc96b2d/none)
[2017/03/16 17:02:46 +07] [INFO] Enterprise Enabled: false
[2017/03/16 17:02:46 +07] [INFO] Current working directory is /mattermost/bin
[2017/03/16 17:02:46 +07] [INFO] Loaded config file from /mattermost/config/config.json
[2017/03/16 17:02:46 +07] [INFO] Server is initializing...
[2017/03/16 17:02:46 +07] [INFO] Pinging SQL master database
[2017/03/16 17:02:47 +07] [CRIT] Failed to ping DB err:pq: no pg_hba.conf entry for host "172.16.100.100", user "mmuser", database "mattermost", SSL off

The only solution for me - remove string with search from /etc/resolv.conf

`~/mattermost-docker$` git branch -v
\* master              fb26800 Update to Mattermost 3.7.1`

**Comment by Twilek-de** [comment]
Maybe it is connected. No matter what I do. I get a 
```
db_1   | LOG:  database system was shut down at 2017-03-20 23:07:22 CET
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  incomplete startup packet
```

when starting up the docker containers. The app container and the web container will not connect to the database. The log shows a repeated 
```
[2017/03/20 23:08:54 CET] [INFO] Server is initializing...
[2017/03/20 23:08:54 CET] [INFO] Pinging SQL master database
[2017/03/20 23:09:04 CET] [CRIT] Failed to ping DB err:dial tcp 46.38.243.234:5432: i/o timeout
```

**Comment by xcompass** [comment]
@aatangulov and @Twilek-de how did you start your containers? Were you using docker-compose?

**Comment by Twilek-de** [comment]
Yep docker-compose with standard config file and changed ports due to my setup-

**Comment by xcompass** [comment]
Indeed, it seems that you have `db` resolved differently from your DNS (possibly in resolve.conf). To workaround this, you can change the db container's name into something else and add DB_HOST environment variable to the app container, e.g.

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 5d1622c..79d01d0 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,7 +2,7 @@ version: "2"

 services:

-  db:
+  db1:
     build: db
     restart: unless-stopped
     volumes:
@@ -36,8 +36,9 @@ services:
       - MM_USERNAME=mmuser
       - MM_PASSWORD=mmuser_password
       - MM_DBNAME=mattermost
+      - DB_HOST=db1
     depends_on:
-      - db
+      - db1

   web:
     build: web
```

I tested it locally. Let me know if it works for you.

**Comment by pichouk** [comment]
Is this solved ? @aatangulov @Twilek-de

**Comment by Twilek-de** [comment]
I have switched to a locally installed mattermost.

**Comment by andlinger** [comment]
I have the same problem now. Funny, it shows the same ip as @Twilek-de 
mattermost.log says: 

```
{"level":"info","ts":1527723572.5220578,"caller":"sqlstore/supplier.go:198","msg":"Pinging SQL master database"}
{"level":"error","ts":1527723582.5225577,"caller":"sqlstore/supplier.go:210","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp 46.38.243.234:5432: i/o timeout"}
```

**Comment by pichouk** [comment]
Hi @andlinger did you try the [suggested workaround](https://github.com/mattermost/mattermost-docker/issues/113#issuecomment-307229820) ? 
If you want to find the root cause, maybe you should check if there is a reason that your container resolve `db` DNS record as this IP ? Are you using a specific deployment platform/cloud provider ? What is the result of a DNS resolution for `db` on your host server ?

**Comment by andlinger** [comment]
Fixed it. 
In resolv.conf was a search-domain configured. After removing this entry everything is working as expected.
