### ISSUE TITLE
Update to Mattermost 3.8.1

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#118]
Hi @xcompass

Wonder if I can ask your help to update the mattermost-docker repo to version 3.8.1 please?

Download links and hashes can be found [here](https://pre-release.mattermost.com/core/pl/dtdg7zn733gm3cn4c8bpcwmfke) if needed.

Thanks :)

**Comment by xcompass** [comment]
Thanks @lindy65 for the heads up. It's already updated earlier today. https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile#L8

**Comment by lindy65** [comment]
Fantastic :)  Thanks @xcompass !
