### ISSUE TITLE
Help update to version 3.9.0

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#123]
Hi @xcompass

Wonder if I can ask your help to update the mattermost-docker repo to version 3.9.0 please?

Thanks :)

**Comment by pichouk** [comment]
There is already PR #122 which update this repository to 3.9.0
If you don't want to wait for the PR to be merged, you can just apply the following changes : https://github.com/mattermost/mattermost-docker/pull/122/files
Basically, you just have to change the `ENV MM_VERSION` variable to `3.9.0` in the `app/Dockerfile` file :)

**Comment by lindy65** [comment]
Ah, thank you @pichouk!  I did not see the pull request.  I'll close off this issue :)
