### ISSUE TITLE
DB container fails to build

### ISSUE THREAD

**Issue by tumbl3w33d** [mattermost/mattermost-docker#124]
When I build the db container using [this Dockerfile](https://github.com/mattermost/mattermost-docker/blob/master/db/Dockerfile) from current master then the `docker build` fails building the cryptography module for python due to missing openssl and ffi headers.

Fix:
Add installation of packages `libssl-dev` `libffi-dev`.

**Comment by thomasnaudin** [comment]
Same problem here, @tumbl3w33d solution worked for me. Thanks :)

**Comment by ipsecguy** [comment]
Same here:

`creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory

     #include <openssl/opensslv.h>

                                  ^
    compilation terminated.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status `

**Comment by pichouk** [comment]
Should be now fixed by #129

**Comment by tumbl3w33d** [comment]
Good stuff, thanks.
