### ISSUE TITLE
Web container bash variable $PLATFORM_PORT_80_TCP_ADDR

### ISSUE THREAD

**Issue by Psidium** [mattermost/mattermost-docker#13]
Hello guys!

I'm trying to deploy this instance, but in my environment, the `web` container can't find a variable called `$PLATFORM_PORT_80_TCP_ADDR` in the file `docker-entry.sh`, thus making nginx exit.

Please look at my fork in https://github.com/Psidium/mattermost-docker to see the changes I've done (mostly to address a issue I had with proxys in my corporate level).

Where this variable was supposed to come from?

thank you,
Psidium

**Comment by Psidium** [comment]
Okay, I managed to make a 'fallback' for this is issue in my case:
```bash
if [ -z "$PLATFORM_PORT_80_TCP_ADDR" ]
then
  echo "can't find platform_port_80_tcp_addr" > /dev/stderr
  ping -c 7 platform &> /dev/null
  if [ $? -ne 0 ]
  then
    echo "can't connect to 'platform'" > /dev/stderr
    exit 7
  fi
  PLATFORM_PORT_80_TCP_ADDR=$(getent hosts platform | awk '{ print $1 }')
  PLATFORM_PORT_80_TCP_PORT=80
fi
```

**Comment by npcode** [comment]
`PLATFORM_PORT_80_TCP_ADDR` variable comes from `link` option of docker-compose but I think it may not work in version 2 which you are using.

> Environment variables will only be populated if you’re using the legacy version 1 Compose file format.
>
> --  https://docs.docker.com/compose/link-env-deprecated/

**Comment by npcode** [comment]
I haven't find the best way to get the port. I guess setting the port as an environment in docker-compose.yml might be an easy solution.

    environment:
     - PLATFORM_PORT_80_TCP_ADDR=80
