### ISSUE TITLE
Add a bot/PRcheck to verify that a contributor signed the CLA

### ISSUE THREAD

**Issue by pichouk** [mattermost/mattermost-docker#134]
As described in [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) each contributor should signed the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/) to be add to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true).

Could be great to add a bot or a label which will block a PR to be merge until submitter signed the CLA.
Should look on project [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) where something like that is implemented.

**Comment by pichouk** [comment]
Some information here : https://developer.github.com/v3/repos/statuses/

**Comment by jasonblais** [comment]
@pichouk We pointed this [Mattermod](https://github.com/mattermost/mattermost-mattermod) to this repo as well, which should trigger a CLA note if the contributor hasn't signed it yet.

**Comment by pichouk** [comment]
Quick and perfect :) Thanks !
