### ISSUE TITLE
Newer mattermost-prod-app containers appear to not save config changes

### ISSUE THREAD

**Issue by br00tal** [mattermost/mattermost-docker#136]
Hi,

It appears that newer versions of this container are not able to save config changes (i.e. things changed in the `System Console`).  I noticed this when, after updating yesterday, my Mattermost install went into `Preview Mode`.  I went into the `System Console` to re-enable sending emails, clicked save, and it immediately went back to `false` again.

I tried to view more detailed logs, and tried to change the log level to `DEBUG`, but just like the email setting, it refused to save my change and reverted back to its default setting of `INFO`.

I also tried to manually edit the `config.json` file to enable email notifications, but that didn't seem to work.  The entry in the file stayed set to `true`, but in the `System Console` web UI, it was still set to `false`.

I then reverted back to container id `91905885c2b2` (https://hub.docker.com/r/mattermost/mattermost-prod-app/builds/bfebjwpehhhjdayqbdsxipm/), and everything works as expected again.  At the time of this writing, there appears to be two newer containers, and I believe I tried both of them, and they both seemed to exhibit the same issue.

Thanks!

**Comment by pichouk** [comment]
Hi,
I noticed this issue yesterday but was not able to fix it today, I'll work on it in couple hours.

**Comment by br00tal** [comment]
Sounds like a plan.  Thanks for the quick response!

**Comment by pichouk** [comment]
It was introduced by PR #131 which now use environments variable to override Mattermost default configuration (some explanations [here](https://docs.mattermost.com/administration/config-settings.html)).
I'm on it, but it might ends up with a revert since it seems that environments variable override configuration **and** disable possibility to change anything...

**Comment by MichaelEischer** [comment]
Just in case that you restore the config file: Please remove the hardcoded salts! These should be different for each installation and kept secret, not included in a docker container.

**Comment by pichouk** [comment]
@MichaelEischer I know. You can open a new issue about that.
A solution was proposed on PR #31 but was not merge. It is on the TODO of the refactoring project :)

**Comment by MichaelEischer** [comment]
The new issue will have to wait until this issue is resolved. Until then there's no config file to fix.

**Comment by pichouk** [comment]
Actually, salts are still hardcoded. There are in Dockerfile (see `ENV` instructions). And solving this issue will probably deplace those hardcoded values to `docker-entry.sh`. So the problem is still here and should be solved.
