### ISSUE TITLE
Drop docker-compose v1 support ?

### ISSUE THREAD

**Issue by pichouk** [mattermost/mattermost-docker#138]
This is not a really important thing, but is the `docker-compose-v1.yml` file to keep `docker-compose` version 1 support still needed ? It is not a "deprecated" version, but Docker describe it as "legacy".

Any objections ?  (cc @xcompass @jasonblais )

**Comment by xcompass** [comment]
I kept it there just in case someone still on very old version. I'm happy to drop it if no one is using it.

**Comment by pichouk** [comment]
I'm quite confident that the version 1 is not used because it is not the default version on this repository, and there is no "breaking changes" which could encourage to use the version 1.

I'll let this issue open for few days. If nobody contest I'll delete `docker-compose-v1.yml`.

**Comment by xcompass** [comment]
Sound good!
