### ISSUE TITLE
Help update to v3.10

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#143]
Hi @xcompass

Wonder if I can ask your help to update the mattermost-docker repo to version 3.10.0 please?

Thanks :)

**Comment by pichouk** [comment]
The repository is already updated for Mattermost 3.10.0. I just create a [Github release](https://github.com/mattermost/mattermost-docker/releases/tag/3.10.0) which, I guess, should trigger a Docker build on docker hub.

**Comment by pichouk** [comment]
I confirmed that is was pushed with the `3.10.0` tag to Docker Hub.
