### ISSUE TITLE
FR add ability to deploy with swarm

### ISSUE THREAD

**Issue by pastukhov** [mattermost/mattermost-docker#147]
Please upgrade docker-compose.yml to version 3.
It make able to run mattermost on swarm cluster with ``` docker stack deploy ```

**Comment by pichouk** [comment]
Seems related with #104

**Comment by pichouk** [comment]
@pastukhov Are you sure that supporting docker-compose version 3 will allow to use Docker stacks with Swarm ? 
https://github.com/mattermost/mattermost-docker/pull/148#issuecomment-326603278 seems to say it will not.

**Comment by pdemagny** [comment]
@pichouk I have written & tested a swarm mode ready yml file, how can i share it with you ?

**Comment by pichouk** [comment]
@pdemagny A Github gist can be a good way ;) Or a pastebin if you prefer.

**Comment by pdemagny** [comment]
@pdemagny or a PR :)

**Comment by pichouk** [comment]
@pdemagny Sure ! I'm interesting, but I understood [here](https://docs.docker.com/docker-cloud/apps/stacks/) that a Docker compose file should allow to use `docker stack`

**Comment by pdemagny** [comment]
@pichouk that depends.
With docker-compose you mostly build and run on a single docker engine (usually your laptop) for development purposes.
The big difference with docker stack (swarm mode of the main docker engine binary) is that you can build images at stack creation but they would only live on a single node of your swarm cluster (the on where you run the docker stack deploy command), which is totally pointless.
Swarm is meant to run pre-built images of your micro-services spreaded across several docker engines (this is a better fit for production of course) as explained here: https://docs.docker.com/compose/swarm/#limitations

I've made a compose v3.3 file fully compatible with docker swarm mode for myself, utilizing your prod-app & prod-db docker hub images. Its no big deal but i'd be glad to contribute it on this project, if that's ok with you.
How should i proceed ? (i'm a sysadmin not a github guru, a little guidance would be nice).
Requirements & installation procedures differs, shall i update the README.md accordingly ?

**Comment by pichouk** [comment]
@pdemagny Great !
If you have something working, you can fork this repository and add your modifications (docker-compose file and documentation) to your forked repository. Then, [submit a Pull Request](https://github.com/mattermost/mattermost-docker/pulls) and we will discuss and, I hope, merge your commits :)

**Comment by pichouk** [comment]
Thanks to @pdemagny and PR #176, swarm mode is now supported !
