### ISSUE TITLE
Docker requirement for this repository

### ISSUE THREAD

**Issue by pichouk** [mattermost/mattermost-docker#151]
Before to merge PR #148, I would like to open a discussion about the Docker requirement of this repository. Mattermost have OS/software/web client requirements, and I guess we should add a Docker requirement on our repository too. It should be better if we are clear on what versions we support, what version we will no longer support, and will allow to identify and announce breaking changes (eg. using a new functionality of `docker-compose`).

To begin, I think we can add versions requirement for `docker-engine` and `docker-compose` on the README. I propose :
- `1.13.0+` for Docker
- `3.0+` for Docker Compose

**Comment by pichouk** [comment]
Any opinion on this @xcompass or @jasonblais ?

**Comment by jasonblais** [comment]
@pichouk I agree we should add version requirements in README, perhaps even to our install guides
 - https://docs.mattermost.com/install/prod-docker.html
 - https://docs.mattermost.com/install/docker-local-machine.html

As for the actual Docker version numbers, I don't have a strong opinion.

Would you have thoughts on how many might be affected if we restrict to 1.13.0+ for Docker and 3.0+ for Docker Compose

**Comment by pichouk** [comment]
Docker `1.13.0+` allow to use docker-compose `3.0+`, which allow to support the "future" of docker-compose : docker stack. And we have some [demands about this](https://github.com/mattermost/mattermost-docker/issues/104).
**BUT** I know that some people use the Ubuntu packaged Docker binary instead of the official (called `docker.io`). I don't know how many people it affect, but this package is, AFAIK, on `1.12.x`. So it could break things for those people.

From here, we have 3 solutions :
- we support docker-compose `3.0+` and we consider people should have an almost up-to-date Docker version
-  we do not support docker-compose `3.0+` so we could announce "only" Docker `1.12+` as requirement
- we announce Docker `1.12+` but we propose both `2.0` and `3.0` docker-compose files
 
According to me, maintaining 2 docker-compose files is dirty since, for now, the only difference is the first line, specifying the version number to use. But I also understand that some people may use sensitive systems and prefer to wait few months before updating Docker, and `1.13.0` is only 7 months old.

If I was the only one to decide, I will use the `1.13.0+` and `3.0+` requirements. I guess this is not a really strong and complicated to achieve requirements, but maybe some people will need an update (I have no metrics to say how much). But I can understand if Mattermost want to be more permissive about requirements.

**Comment by jasonblais** [comment]
Maybe we can post about it in the forums and see if there's any pushpack for increasing the Docker version requirement to 1.13.0+? https://forum.mattermost.org/

If not, we should consider timing the version requirement increase with Mattermost 4.1 release, so we can highlight it in the changelog and/or release announce.

I think the principle to use is `no surprises`. If we communicate with the community (and listen to their feedback), we should be okay

**Comment by pichouk** [comment]
Probably a wise idea to ask community on the forum. I just open [a thread](https://forum.mattermost.org/t/mattermost-with-docker-discussion-about-requirements/3518) ;)

**Comment by ionbasa** [comment]
Just a thought. Many people who use this in a production environment will rely on Ubuntu LTS releases. 16.04 is the current LTS release and so far the package version only goes up to 1.12.6
See: https://launchpad.net/ubuntu/xenial/+source/docker.io

I'd recommend sticking with v2 until LTS releases get 1.13

**Comment by pichouk** [comment]
Sure, but the `docker.io` package is always late on Docker version... Don't think it's a good practice to use it. I always use Docker maintained package in production environment, I never got problem with this.

**Comment by pichouk** [comment]
After some discussions, I will set some "requirements" on the README file.
As @jasonblais say, the principle is `no surprises` so requirements will be Compose 1.6.0+ and Docker Engine 1.10.0+, which allow to use the current `docker-compose.yml` file (format 2.0) of this repository.

We don't need to support Compose format `3.0+` since a PR is currently open to add support for docker stacks. I'm closing this issue for now.
