### ISSUE TITLE
Update to Mattermost v4.1

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#164]
Hi @pichouk,

Wonder if I can ask your help to update the mattermost-docker repo to version 4.1.0 please?

You can find the changelog [here](https://docs.mattermost.com/administration/changelog.html#release-v4-1-0) and download links [here](https://pre-release.mattermost.com/core/pl/kw58b88e1f8c5pfcukkt156d1e)

Thanks!

**Comment by pichouk** [comment]
Sorry, I missed this month minor update...
Changelog seems ok for me, no braking changes. I just created PR #165 and wait for the Travis tests to be OK. WIll merge and tag in few minutes.

**Comment by pichouk** [comment]
Seems good 👍
