### ISSUE TITLE
Help update to Mattermost v4.2?

### ISSUE THREAD

**Issue by lindy65** [mattermost/mattermost-docker#170]
Hi @pichouk,

Mattermost v4.2 release is officially out.

You can [view the full changelog for Mattermost 4.2 here](https://docs.mattermost.com/administration/changelog.html#release-v4-2-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/rfmj6xak9irifx5598j3jtgadc).

Thanks for maintaining Mattermost Docker!

**Comment by pichouk** [comment]
PR #169 just did it :)

**Comment by lindy65** [comment]
Thanks!
