### ISSUE TITLE
Adding watchtower?

### ISSUE THREAD

**Issue by ionbasa** [mattermost/mattermost-docker#172]
What is the dev team opinion on adding watchtower? Watchtower allows for containers to be automatically updated when new releases happen, thus making downtime minimal. https://github.com/v2tec/watchtower

I haven't tried this yet, but I may experiment with it on my own server. My setup is a bit different than most people though, I don't run the db and web service, since I already have those setup separately. 

I'd love to hear thoughts on this, hopefully I can share my findings.

**Comment by pichouk** [comment]
Interesting, I didn't know Watchtower, seems to be a great tool. However, it seems to be a specific tool that people can choose or not to use. IMHO this tool should not be add on the repository, but if you write a documentation on how deploy Mattermost with Watchtower, it could be interesting.

**Comment by ionbasa** [comment]
I wouldn't mind writing up documentation on how to set it up and sharing what I learned. I have one docker-compose container that uses Watchtower and that is Portainer: https://github.com/portainer/portainer-compose

It seems to work extremely well once it's setup.  I'll try adding it to my Mattermost container and see how it goes, it would let me make upgrades to MM server with almost no intervention on my part.

**Comment by pichouk** [comment]
Ok !
If you want to add few lines on how to deploy with those tools, feel free to submit a pool request :) Meanwhile, I close the issue :)

**Comment by pushpdeep** [comment]
> I wouldn't mind writing up documentation on how to set it up and sharing what I learned. I have one docker-compose container that uses Watchtower and that is Portainer: https://github.com/portainer/portainer-compose
> 
> It seems to work extremely well once it's setup. I'll try adding it to my Mattermost container and see how it goes, it would let me make upgrades to MM server with almost no intervention on my part.

Hi, I want to deploy mattermost using portainer . Any idea on how to do this ?
