### ISSUE TITLE
 Error: Unable to create user. Error: CreateUser: api.user.create_user.accepted_domain.app_error,

### ISSUE THREAD

**Issue by yocode** [mattermost/mattermost-docker#184]
After connecting a shell to the mattermost_app container. I receive this error when trying to create a user.

[2017/10/18 17:16:40 UTC] [WARN] The database schema version of 4.3.0 appears to be out of date
[2017/10/18 17:16:40 UTC] [WARN] Attempting to upgrade the database schema version to 4.4.0
Error: Unable to create user. Error: CreateUser: api.user.create_user.accepted_domain.app_error,
Usage:
  platform user create [flags]

**Comment by pichouk** [comment]
Hi, it seems to be a Mattermost issue, not a Docker one.
[An issue about this is open](https://github.com/mattermost/mattermost-server/issues/7654). I let you see there ;)

**Comment by pichouk** [comment]
Seems that the new `4.3.1` version fix this. I just upgraded the Docker images :)
