### ISSUE TITLE
Mattermost in Docker with MySQL starts with wrong port

### ISSUE THREAD

**Issue by matthias-scholze** [mattermost/mattermost-docker#190]
Hello,
I try to use mattermost docker version with an outside mysql instance. I'm sure that I have done all needed configuration for my mysql instance in yml file and checked mattermost/conf/config.json to.

If I start docker-composer up I get the following output:

app_1  | Wait until database 192.168.0.75:5432 is ready...

It tries on the wrong port. Has anybody a suggestion?

Thnaks Regards
Matthias

**Comment by pichouk** [comment]
Can you provide your `docker-compose.yml` file please (don't forget to remove credentials) ?
`app` container will try to reach your database on the port defined by environment variable `DB_PORT_NUMBER` (which is, by default, 5432). So I think your environment variable is not set.

**Comment by matthias-scholze** [comment]
@pichouk Thanks! I used DB_PORT instead of DB_PORT_NUMBER
