### ISSUE TITLE
has the file storage location changed? 

### ISSUE THREAD

**Issue by hcientist** [mattermost/mattermost-docker#192]
I installed mattermost this way back in august or september. I recently updated to 4.3.1, and am wondering if the static file paths changed somehow. I had to re-upload my profile image, and while it sitll remembers the names of several custom emoji, and I can confirm their images are stored at `/mattermost/data/emoji` (and the corresponding host directory form my volume mapping in the `docker-compose.yml` file), the images are not visible when using those emojis. Also, when i add a new custom emoji that seems to work, it is not added to the above location(s)

**Comment by jasonblais** [comment]
Hey @hcientist, 

In v4.2.0 and later, uploaded file attachments are now grouped by day and stored in `/data/<date-of-upload-as-YYYYMMDD>/teams/... ` of your file storage system.

For other important notices, see https://docs.mattermost.com/administration/important-upgrade-notes.html

**Comment by pichouk** [comment]
@hcientist Is your problem solved ?
