### ISSUE TITLE
Get rid of quote for mysql

### ISSUE THREAD

**Issue by nspina** [mattermost/mattermost-docker#193]
in the readme

MM_SQLSETTINGS_DATASOURCE : MM_USERNAME:MM_PASSWORD@tcp(DB_HOST:DB_PORT_NUMBER)/MM_DBNAME?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"

That quote at the end threw me off for ages as I thought there was a quote missing at the beginning. It should read: 

MM_SQLSETTINGS_DATASOURCE : MM_USERNAME:MM_PASSWORD@tcp(DB_HOST:DB_PORT_NUMBER)/MM_DBNAME?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s

**Comment by pichouk** [comment]
Thanks @nspina 
I just fixed it :)
