### ISSUE TITLE
Outgoing hook not working

### ISSUE THREAD

**Issue by MRdotB** [mattermost/mattermost-docker#200]
Hello,

Look like Outgoing hook are not working.
On mattermost-docker stack I'm unable to trigger a Outgoing hook.
I try with different hook config channel, no channel, world, all.
I don't see any outgoing hook on the logs.
I try to create some Incoming webhook and the log appear.

Thanks

**Comment by pichouk** [comment]
I have some working outgoing webhooks so I think there is something in your configuration.

Can you provide some informations about your configuration : 
- your webhook configuration
- how did you catch the hook ? Maybe some little piece of code ?

I'll try to understand and reproduce if possible.

**Comment by MRdotB** [comment]
Ok after doing some test on the config file if I set the logLevel to DEBUG and console to true
I can see the outgoing hook log.
Sorry
