### ISSUE TITLE
Any plans on update to lattermost 3.0.1 ?

### ISSUE THREAD

**Issue by snadal** [mattermost/mattermost-docker#21]
I tried to update Dockerfile 

```
FROM ubuntu:14.04

RUN apt-get update && apt-get -y install wget nectar
RUN mkdir -p /mattermost/data

RUN wget https://releases.mattermost.com/3.0.1/mattermost-team-3.0.1-linux-amd64.tar.gz \
        && tar -xvzf mattermost-team-3.0.1-linux-amd64.tar.gz && rm mattermost-team-3.0.1-linux-amd64.tar.gz

COPY config.template.json /
COPY docker-entry.sh /

RUN chmod +x /docker-entry.sh
ENTRYPOINT /docker-entry.sh

EXPOSE 80
```

And it launches ok, but when I change anything on System Console the system returns always this error:

`We received an unexpected status code from the server. (500)`

Also, this error appears many times in the system log:

`[2016/05/17 01:02:36 UTC] [EROR] /api/v1/websocket: code=404 ip=[IP_ADDR]`

Any hints ?

**Comment by npcode** [comment]
I'm waiting for the new mattermost release with fix for the bug you mentioned...

**Comment by npcode** [comment]
I have updated it to 3.0.2 since the bug was fixed.

**Comment by snadal** [comment]
Great ! Thanks !
