### ISSUE TITLE
Mattermost preview build docker is truncating action json in message

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [mattermost/mattermost-docker#214]
Hi Team,

The one line install mattermost preview - truncates the action json when button attachment is invoked and hence button is not getting displayed in mattermost GUI.

Please note I am using hubot-matteruser adapter.

**Comment by pichouk** [comment]
I don't understand your issue, but the preview image is maintained on [mattermost/mattermost-docker-preview](https://github.com/mattermost/mattermost-docker-preview).
