### ISSUE TITLE
Mattermost Platform CLI Hangs

### ISSUE THREAD

**Issue by Hunga1** [mattermost/mattermost-docker#215]
The Mattermost `platform` command hangs (does not return from execution) on various commands with a fresh Mattermost container. Only after creating an initial user and team, making a change in the System Console to a setting (i.e. SiteURL), and saving changes to the configuration `config.json` does the platform command start to work properly.

Various platform commands that I found were hanging on a fresh Mattermost container were:
```
platform version
```
```
platform user create --email admin@example.com --username admin --password password
```

Attached are two `config.json` files. One from a fresh Mattermost container, and the other from a Mattermost container after an initial user and team was created, and the SiteURL was updated in the web client's System Console.

[initial_config.txt](https://github.com/mattermost/mattermost-docker/files/1564255/initial_config.txt)
[siteurlUpdated_config.txt](https://github.com/mattermost/mattermost-docker/files/1564256/siteurlUpdated_config.txt)

**Comment by watadarkstar** [comment]
@Hunga1 I don't know if this helps you:

I run `go build ./cmd/platform` to build the command.

**Comment by watadarkstar** [comment]
Have you tried to run `go build ./cmd/platform` to build the command?

**Comment by pichouk** [comment]
Did you try on a Mattermost instance not deploy on Docker. I think this is a behavior from the `platform` command, not from our Docker image. Maybe you should submit an issue on the [`mattermost-server`](https://github.com/mattermost/mattermost-server) repository.

**Comment by Hunga1** [comment]
Thanks for the suggestions!

Yes, it may be caused by the platform command and not the Mattermost docker image.

I’ll try these two approaches and see what further troubleshooting finds. I’ll reply back to with the results.

**Comment by Hunga1** [comment]
I've finished further troubleshooting with your suggestions. I've discovered that the when you compile and run the `[mattermost-server](https://github.com/mattermost/mattermost-server)` from source, and compile the `platform` CLI utility with the command @watadarkstar provided (`go build ./cmd/platform`), the `platform` command works fine.

Unlike the `platform` command found in the Docker image, the one compiled from source does not hang when executing `platform version` or `platform user create` commands.

Notes:
- To compile the `mattermost-server` from source, I followed the [Mattermost - Installing Developer Components on Mac OS X Guide](https://docs.mattermost.com/developer/dev-setup-osx.html)

- To access the `platform` command on the `mattermost-docker` app container, I used a bash shell with `sudo docker exec -i -t <CONTAINER_ID> /bin/bash`

**Comment by Hunga1** [comment]
I did notice the initial value of `SQLSettings.DataSource` in my fresh `mattermost-docker` application container's `config.json` file was:
```
mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
```

If I updated the value in `config.json` (via the shared volume) to what the connection string should be in relation to my `docker-compose.yml` settings, the `platform` command seemed to work fine after.
```
postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable\u0026connect_timeout=10
```

On a fresh container, I noticed the `SQLSettings.DataSource` changed to the expected value after opening the System Console and saving any change (or no change for that matter) in the General Configurations panel.

**Notes:**
The only changes I have to my `docker-compose.yml` file are the follow:
- Enabling the team edition
- Adding `DB_HOST=db` to the app container's environment
- Adding `DB_PORT_NUMBER=5432` to the app container's environment

**Comment by pichouk** [comment]
That's confusing, I cannot reproduce what you describe. If I start a new container I have no issues to run `platform` commands.

```
$ git clone git@github.com:mattermost/mattermost-docker.git && cd mattermost-docker
$ docker-compose build
[...]
$ docker-compose up -d
$ docker exec -it mattermostdocker_app_1 platform version                                                                                                                          [22:33:53]
Version: 4.5.0
Build Number: 4.5.0
Build Date: Fri Dec 15 23:15:33 UTC 2017
Build Hash: 03f5c939deb4a6ab2fd01639b5570799e4118bab
Build Enterprise Ready: true
DB Version: 4.5.0
```

**Comment by Hunga1** [comment]
Thanks. I'm not sure what's going on with my original clone of the repository. I cloned the repository again, applied the diff, and it seems to work fine now. Probably user error :|

You can close this issue now. Thanks for the assistance.
