### ISSUE TITLE
Made Plugins works

### ISSUE THREAD

**Issue by pichouk** [mattermost/mattermost-docker#217]
As [some people](https://forum.mattermost.org/t/a-problem-with-plugins-start-up-with-docker-installation/4263/5) have noticed, Plugins are not working well.

At `app` container startup, there is the following error:
```
[2017/12/19 19:53:14 CET] [EROR] failed to start up plugins: mkdir ./client/plugins: no such file or directory
```
Current workaround is to disable Plugins.

We should investigate on how Plugins works, what they need (eg. a `./client/plugins` folder), if it change our default `config.json` file (eg. to enable or disable by default), etc. before it is still a beta feature ;)

Some links to help:
- [Mattermost Plugin documentation](https://docs.mattermost.com/administration/plugins.html)
- [Forum post to track Plugin related issues](https://forum.mattermost.org/t/mattermost-plugins-in-beta/4123/3)

**Comment by LordVeovis** [comment]
I have the same issue

The process pwd is /mattermost/bin
When I enable the plugins functionality, I see the same error messages and below is the content of the bin dir:

```
root@ceea89fbe9c2:/mattermost/bin# ll
total 48580
drwxr-xr-x 1  106  111     4096 Dec 30 13:25 ./
drwxr-xr-x 1  106  111     4096 Dec 16 00:17 ../
-rwxr-xr-x 1 root root 49731993 Dec 27 22:26 platform*
drwxr--r-- 2 root root     4096 Dec 30 13:25 plugins/
root@ceea89fbe9c2:/mattermost/bin# ll plugins/
total 8
drwxr--r-- 2 root root 4096 Dec 30 13:25 ./
drwxr-xr-x 1  106  111 4096 Dec 30 13:25 ../
```

So the process attempt to create 2 directories (./plugins and ./client./plugins) in /mattermost/bin, which is the problem as bin :
* is the wrong place to store data
* is not persistent related to the docker volume mapping

For the error, the process attempt to create a directory (plugins) in a non-existing directory (client)

**Comment by LordVeovis** [comment]
If I attempt to create a client directory in /mattermost/bin (as directory or symbolic link to /mattermost/data/client), I get 404 from the server for all requests

**Comment by LordVeovis** [comment]
I have been able to fix this issue with the following changes on my docker-compose.yml:

app:
    working_dir: /mattermost
    command: /mattermost/bin/platform

**Comment by pichouk** [comment]
Thanks to @LordVeovis, plugins should works now.

We don't need to add any change to the default config file, so closing this issue :)

**Comment by sadsfae** [comment]
I get this error upgrading from ```4.5.0``` to ```4.6.0``` on a standard CentOS7 install using the official version.  My workaround was to make this directory manually.

```
mkdir /opt/mattermost/client/plugins
chown -R mattermost.mattermost /opt/mattermost
```
