### ISSUE TITLE
Upload image to Docker Hub

### ISSUE THREAD

**Issue by wgorski-antrego** [mattermost/mattermost-docker#22]
Do you plan to upload the image to docker hub? Currently I can only see https://hub.docker.com/r/mattermost/platform/ which does not support version 3.0.

**Comment by npcode** [comment]
@it33 Would you update the image?

**Comment by StianOvrevage** [comment]
+1 - Would love to see 3.0 on docker hub. Having a bit of challenges setting up mattermail plugin which is optimized for 3.0.

**Comment by it33** [comment]
We should, @StianOvrevage would you join us on https://pre-release.mattermost.com/core in the Developers channel? Please just post there and we can figure out how to get this done. Thanks so much for creating mattermail, would love to have you in discussions with the core team,

**Comment by xcompass** [comment]
@it33, I have a fork that published to dockerhub. Basically you will need to create one dockerhub repo for each component in this repo and point each dockerhub repo to different dockerfiles. so you will have mattermost/app, mattermost/db, etc, on dockerhub.

+1 for this so that I can get rid of my fork.

**Comment by StianOvrevage** [comment]
Credit for mattermail should go to @rodrigocorsi2 and not me! But I'll join you in the dev channel anyhow :)

**Comment by andymac4182** [comment]
It would be great to see this get submitted as a official image to dockerhub. Not sure what is involved but would make it simple to get started and up to date.

**Comment by it33** [comment]
Sorry for late reply, @crspeller was working on this and he's away for the holiday weekend in Canada, @xcompass, is there a PR you can do to help prepare this repo to get pushed to Docker Hub? I'm not familiar with setup. @npcode, wondering if you have any thoughts?

**Comment by npcode** [comment]
@it33 I completely agree with uploading the images in this repository to dockerhub. It would be nice if I can help it.

**Comment by xcompass** [comment]
@it33 you have all the code you need. No need to change the code or any PR. You just need to do the setup in docker hub. Creates three automated builds, one for app, one for db and one for web. In each build, change dockerfile location to the correct path,e.g. for app, it should be /app
<img width="1265" alt="screen shot 2016-05-22 at 00 18 05" src="https://cloud.githubusercontent.com/assets/465548/15452893/2ead0082-1fb3-11e6-9541-03d7c95a28d7.png">
Then you will have three automated build images. That's it.

**Comment by npcode** [comment]
@xcompass @it33 Additionally we can send a PR to https://github.com/docker-library/official-images to make them official images which can be found in https://hub.docker.com/explore/.

**Comment by xcompass** [comment]
Good idea!

**Comment by it33** [comment]
Thanks @npcode, @xcompass when @crspeller is back he can review and approve the ideas. Sorry for the delay, our monitoring systems in Mattermost work on /platform but we don't have them setup for /mattermost-docker yet. @esethna is back this week and we can ask his help to connect up all the Mattermost projects outside of /platform. 

Please do feel free to join our [Developers channel](https://pre-release.mattermost.com/core/pl/6tshmq6c4in55m95knew3drq6a) on our Mattermost instance if you'd like to be more involved in the community.

**Comment by wgorski-antrego** [comment]
As I can see, you already have a docker repository for mattermost: https://hub.docker.com/r/mattermost/platform/~/dockerfile/. 
Looking at the Dockerfile, it seems like the change would be really trivial. Assuming that the location of the mattermost.tar.gz file on s3 has not changed, perhaps you would just have to rebuild the docker image and push it as version 3.0?

**Comment by crspeller** [comment]
I have redone the old preview image. It now lives here: https://hub.docker.com/r/mattermost/mattermost-preview/
With a new single line install:
```
docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
```

For this production image I have created three automated builds:
https://hub.docker.com/r/mattermost/mattermost-prod-app/
https://hub.docker.com/r/mattermost/mattermost-prod-db/
https://hub.docker.com/r/mattermost/mattermost-prod-web/

However the web autobuild fails with 
```
Build failed: lstat cert/cert.pem: no such file or directory
```

@npcode Can we have your help fixing the web image then performing any necessary updates to pull the images from these locations.
Thanks!

**Comment by npcode** [comment]
@crspeller To fix the problem, we should not try to copy cert files into web container. I'll modify the Dockerfile and docker-compose.yml to mount the files instead.

**Comment by npcode** [comment]
@crspeller I have just removed the dependency on cert files. Would you please try it again?

**Comment by crspeller** [comment]
@npcode Seems to have worked! After your done modifying the compose files to use the new images on docker hub. Can you tag the repository `3.0`. That way a tag will be created in dockerhub so people can pull a 3.0 image.

**Comment by npcode** [comment]
@crspeller 

> Can you tag the repository 3.0

Well, why not 3.0.2?

**Comment by npcode** [comment]
@crspeller I have tagged this repository as 3, 3.0 and 3.0.2. I hope what I did doesn't conflict with the tagging convention of dockerhub.

**Comment by crspeller** [comment]
@npcode In the past we have not tagged dot releases. But it's fine if you want to maintain that. 
I think everything is done for this issue. Closing.
