### ISSUE TITLE
team-and-enterprise branch no longer exists

### ISSUE THREAD

**Issue by rwillmer** [mattermost/mattermost-docker#221]
I'm trying to upgrade a mattermost-docker installation from a while ago; (mattermost version 3.4).

Following the upgrade instructions, I've done 'docker-compose down'.
https://github.com/mattermost/mattermost-docker#update-mattermost-to-latest-version

But the 'git pull' fails because that branch no longer exists.

It is also referenced on the Maintainer Guide
https://github.com/mattermost/mattermost-docker/blob/master/MAINTENANCE.md

**Comment by ventilooo** [comment]
HI @rwillmer ,

you should rebase your branch on the master of  that project.
And report yourself to the following [line](https://github.com/mattermost/mattermost-docker/blob/8bb026133d7da58456c0eb11976738f90c787b30/docker-compose.yml#L24)


I hope it'll help you

**Comment by rwillmer** [comment]
Thanks for that, I've solved my problem. 

But the bug remains in the Maintainer Guide page linked to above, which references this branch. If it no longer exists, that page should be modified accordingly.

**Comment by pichouk** [comment]
Good point @rwillmer. I just updated this page. Thanks you :)
