### ISSUE TITLE
mattermost/mattermost-prod-web:4.6.0 image build did not start @ docker hub

### ISSUE THREAD

**Issue by thomasf** [mattermost/mattermost-docker#224]
I'm not sure if the build needs to be triggered again but it looks like it.
https://hub.docker.com/r/mattermost/mattermost-prod-web/builds/bqt3hbm4mkdpbnkkftufwzj/

**Comment by pichouk** [comment]
Any idea @jasonblais ?

**Comment by jasonblais** [comment]
@thomasf @pichouk I've contacted our release engineer, thanks for the ping.

**Comment by crspeller** [comment]
Fixed! Thanks for the report @thomasf
