### ISSUE TITLE
Update our production docker image to include the xmlsec library

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-docker#225]
A customer is trying to configure SAML on the production Docker image, which lacks the [xmlsec library](https://www.aleksey.com/xmlsec/download.html). Hence, SAML login fails with the following errors:

```
SAML login was unsuccessful because an error occurred while decrypting the response from the Identity Provider. Please contact your System Administrator. [details: err=exec: "xmlsec1": executable file not found in $PATH : ]
```

Propose we pre-install the xmlsec library on our production Docker image, so that SAML can be configured.

----

@pichouk Thoughts?

**Comment by pichouk** [comment]
Seems ok for me. I just opened a PR, I'll merge if build succeed.

**Comment by DaruinHerrera** [comment]
Quisiera saber si esto tubo solución, 
ModuleNotFoundError at /admin/
No module named 'xmlsec'

docker
