### ISSUE TITLE
Provide tags on hub.docker.com that distinguish by edition

### ISSUE THREAD

**Issue by philippmoeller** [mattermost/mattermost-docker#228]
In my old setup I did not build images myself but got them straight from hub.docker.com. Since the default version changed to Enterprise Edition I need to build images myself.

It would be convenient to have tags that make it possible to choose the correct version **and** edition, e.g.

- mattermost/mattermost-prod-app:4.6.0-team
- mattermost/mattermost-prod-app:4.6.0
- mattermost/mattermost-prod-app:4.6.0-enterprise
- etc.

**Comment by pichouk** [comment]
Already discussed on #202. We cannot auto build different edition on Docker Hub and it is not necessary.
