### ISSUE TITLE
mime types issue that prevent video preview

### ISSUE THREAD

**Issue by gpr** [mattermost/mattermost-docker#229]
I have an issue with the [mattermost/mattermost-prod-app](https://hub.docker.com/r/mattermost/mattermost-prod-app/) image that is related to the point "[Troubleshooting: Unable to play audio or video files on browser](https://github.com/mattermost/docs/blob/5e67ab50bac5a3ddc5febe76facfbf97a9c498d2/source/install/troubleshooting.rst#unable-to-play-audio-or-video-files-on-browser)"

I'm unable to preview attached MP4 video. To fix the issue I binded the  host file `/etc/mime.types` in the container:

```YAML
[...]
volumes:
[...]
  - /etc/mime.types:/etc/mime.types:ro
[...]
```

It would be probably better to make the docker image independent from the host and hence to add `/etc/mime.types` in the image.

**Comment by pichouk** [comment]
Good point :)
We should install `mime-support` package in the Dockerfile to add this file.
We also should find a solution for the [Alpine image we want to use in the future](https://github.com/mattermost/mattermost-docker/pull/208). Maybe the `mailcap` Alpine package should works.
