### ISSUE TITLE
Migrating Postgres  to Container 

### ISSUE THREAD

**Issue by downright770** [mattermost/mattermost-docker#230]
Hi, I'm new to docker and have been running a Mattermost instance for sometime now with the manual setup and install. 
I know how to Migrate from server to server, but not fully understanding how to do this with the container version of postgres. 
I see how to migrate our config, data, and log files. 
Any help in understanding this I would be grateful. 

Thank you

**Comment by pichouk** [comment]
You have 2 options:
- keep your existing database and only use the `app` docker image. Then you need to configure it ([using environment variables](https://github.com/mattermost/mattermost-docker#application-container)) to use your existing database
- migrate your database to Docker. I suggest to use `pg_dump` to get a SQL dump of your existing database and use `pg_restore` to push this dump to your new database (running inside `db` container)

**Comment by downright770** [comment]
Thank you for getting back. 
What I did so far was remove the old database added a new one with same name mattermost. Then changed the user "mmuser" password then granted permissions to the database. 
After that i uploaded the database.  All of that I did my going into the container and changing.
Then I moved over our configuration file. 
Let me know if this is wrong as just learning Docker and how to use as I go here.

**Comment by downright770** [comment]
When doing it the way I explained above I get a 503 error in my browser.

**Comment by downright770** [comment]
here is what I see 

# docker-compose up
Starting mattermostdocker_web_1 ...
Starting mattermostdocker_app_1 ...
Starting mattermostdocker_db_1 ... done
Attaching to mattermostdocker_app_1, mattermostdocker_web_1, mattermostdocker_db_1
app_1  | Using existing config file /mattermost/config/config.json
app_1  | Configure database connection...OK
app_1  | Wait until database db:5432 is ready...
web_1  | linking plain config
web_1  | ln: /etc/nginx/conf.d/mattermost.conf: File exists
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  database system was shut down at 2018-02-01 16:37:06 EST
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  incomplete startup packet
app_1  | Starting platform
db_1   | FATAL:  password authentication failed for user "mmuser"
db_1   | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
db_1   | FATAL:  password authentication failed for user "mmuser"
db_1   | DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"

**Comment by pichouk** [comment]
Did you change correctly the database credentials inside your `docker-compose.yml` file ?

**Comment by downright770** [comment]
yeah it was me being new to docker and docker-compose
I realized that the .yml file is the configuration to change the variables in. Once I did that it worked.
Thank you for the help
