### ISSUE TITLE
db container fails to start with chmod error

### ISSUE THREAD

**Issue by gordontyler** [mattermost/mattermost-docker#24]
```
[gtyler@torgtylervm1 mattermost-docker]$ docker-compose up db
Starting mattermostdocker_db_1
Attaching to mattermostdocker_db_1
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | chmod: changing permissions of ‘/var/lib/postgresql/data’: Permission denied
mattermostdocker_db_1 exited with code 1
```

Running on Centos 7 with:

Docker:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64
```

And docker-compose:

```
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by npcode** [comment]
Hmm.. postgres 9.5 is known to have the bug: https://github.com/docker-library/postgres/issues/116

Did you modify the db Dockerfile to use postgres 9.5 instead of 9.4?

**Comment by gordontyler** [comment]
Nope. I used the 4 line instructions from the docs (clone, link nossl config, compose up -d) and it failed with an error message saying it couldn't link the app container to the db container. So I tried the command I described in the OP to see what was failing in the db container.

**Comment by npcode** [comment]
Would you please delete "- ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data" in your docker-compose.yml and run the container again?

**Comment by gordontyler** [comment]
That worked.

**Comment by gordontyler** [comment]
Although, now I have a separate issue, the app container shuts down after  a minute:

```
[11:02:07 EDT 2016/05/25] [EROR] (main.main:79) Unable to load mattermost configuration file: Error opening config file=config.json, err=open config.json: no such file or directory
```

**Comment by npcode** [comment]
I think you have problems of volume mounting. The error in app container also looks a volume problem because the container load config file from a volume.

Deleting all volume sections in docker-compose.yml may be a workaround but it is not a good long-term solution because you will lost all of data when the containers are removed.

Are you using selinux? Then you may try [this solution](https://forums.docker.com/t/why-does-docker-prompt-permission-denied-when-backing-up-the-data-volume/1484/5).

**Comment by gordontyler** [comment]
I'm not knowingly using selinux. Is it enabled by default in Centos 7?

**Comment by npcode** [comment]
I think so. I have used CentOS 4, 5, 6 and 7 and selinux was enabled in all of them.

**Comment by gordontyler** [comment]
Okay, so after restoring the the postgresql/data volume in docker-compose.yml, I ran the following command:

```shell
sudo chcon --recursive --type=svirt_sandbox_file_t --range=s0 ./volumes/db/var/lib/postgresql/data
```

And then the db container was able to come up.

**Comment by gordontyler** [comment]
Similarly, I had to run the same chcon command for the `./volumes/app/mattermost/config` and `./volumes/app/mattermost/data` folders to fix the app container error I mentioned earlier.
