### ISSUE TITLE
deactivate TLSv1 by default

### ISSUE THREAD

**Issue by cht47** [mattermost/mattermost-docker#242]
Hi, 
today I've seen that TLS 1.0 and 1.1 is on by default under web/mattermost-ssl
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`

I recommend to reject at least TLSv1. Would be nice if we could edit it in the docker-compose.yml.

**Comment by pichouk** [comment]
I'm okay to remove TLS1.0 since it seems that TLS1.1 is widely supported. If you have some others suggestions to improve TLS security on the `web` image I'll be happy to hear about them.

Would you like to submit a PR ? If yes, fell free to submit. Otherwise I can make the change.

**Comment by cht47** [comment]
Thanks, but you can make the change.

As I don't use the standard HTTPS port [SSLLabs](https://www.ssllabs.com/ssltest/) doesn't work for me to check for further vulnerabilities. 

A recommendation (for a TLS1.2 config): 
`ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA;`
There is a huge explanation why these and why this order. Mozilla gives some information about this too.
[Mozilla](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility)
and here you have a generator:
[https://mozilla.github.io/server-side-tls/ssl-config-generator/](https://mozilla.github.io/server-side-tls/ssl-config-generator/)

Enabling HSTS would also be something to think about it. But that can be annoying with cert problems so I don't recommend it for this project.

**Comment by cht47** [comment]
a little update from my side. I will update my container to 5.0 soon and then test some "casual" security configurations without TLSv1 and then some stronger configurations. Then I test it some weeks (colleagues will be my Guinea pigs) and then you will hear from me again with a proper tested working config.

**Comment by minj** [comment]
security > interoperability

drop everything but v1.2, let the unfortunate souls misconfigure their servers on their own

**Comment by J0WI** [comment]
TLSv1.3 support has just been added to nginx on Alpine.

**Comment by pichouk** [comment]
We will probably deprecate the `web` image with #366
