### ISSUE TITLE
"MM_SQLSETTINGS_DATASOURCE" ignored unless "SqlSettings.DataSource" is defined in config.json - not the case by default

### ISSUE THREAD

**Issue by Quentin-M** [mattermost/mattermost-docker#248]
I have seen many users complaining of:
```
[EROR] Failed to ping DB retrying in 10 seconds err=dial tcp: lookup dockerhost on 172.17.0.10:53: no such host
```

This is due to the fact that env variables, as defined by the entrypoint, are ignored if the corresponding key in `config.json` is undefined. An empty value, at least, must be set.

See https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2377#note_49016830.

**Comment by pichouk** [comment]
I can't reproduce this bug. I don't see how it can happen that the `SqlSettings.DataSource` key is null on the `config.json` file ?

If you use `MM_USERNAME` / `MM_PASSWORD` / `MM_DBNAME` variables, the key is set by the entrypoint script. If you use `MM_SQLSETTINGS_DATASOURCE`, it will override the default value which is set inside the `config.json` file.

**Comment by pichouk** [comment]
Hi @Quentin-M, do you have more information on this issue ? :)
