### ISSUE TITLE
"MM_SQLSETTINGS_DATASOURCE" uses a wrong format - protocol is required

### ISSUE THREAD

**Issue by Quentin-M** [mattermost/mattermost-docker#249]
MM_SQLSETTINGS_DATASOURCE is of the form: `postgresql://username:password@host:5232/db`. This generates the following error:

```
Failed to ping db err:Default addr for network ‘host:5432’ unknown
panic: Failed to open sql connection Default addr for network ‘host:5432’ unknown
```

It should have been: `postgresql://username:password@tcp(host):5232/db`

See https://github.com/go-sql-driver/mysql.

**Comment by pichouk** [comment]
I don't understand, how did you get this error ? It works as it is right now and when I try to use your format I doesn't work anymore : `MM_SQLSETTINGS_DATASOURCE` seems to be ignored by the Mattermost server and it fall back to the default value (that you can find [here](https://github.com/mattermost/mattermost-server/blob/master/config/default.json)).

**Comment by pichouk** [comment]
Hi @Quentin-M, do you have more information on this issue ? :)
