### ISSUE TITLE
 Service 'app' failed to build on Windows Server 2019

### ISSUE THREAD

**Issue by gtaspider** [mattermost/mattermost-docker#252]
Hey,

When trying to run `docker-compose up` I got stuck at this error:

> ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /mattermost/data     && if [ "$edition" = "team" ] ; then curl https://releases.mattermost.com/$MM_VERSION/mattermost-team-$MM_VERSION-linux-amd64.tar.gz | tar -xvz ;       else curl https://releases.mattermost.com/$MM_VERSION/mattermost-$MM_VERSION-linux-amd64.tar.gz | tar -xvz ; fi     && cp /mattermost/config/config.json /config.json.save     && rm -rf /mattermost/config/config.json' returned a non-zero code: 4294967295

Trying to find out which command returns 4294967295 (-1) I deleted all commands from the app dockerfile except of the first and found out it seems to be mkdir.

`ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /mattermost/data' returned a non-zero code: 4294967295`

The only thing I changed in the docker-compose.yml is the version (from 2 to 2.1) because I run windows and when I don't do that I always get this error:

`ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`
[See fix here](https://github.com/docker/compose/issues/4106#issuecomment-258590985)

Running Windows Server 2019 17623 pre-release and Docker EE Preview-3 with API Version 1.33 (Client) and 1.34 (Server)

tia,
Spider

**Comment by pichouk** [comment]
Hi !
Do you have any other log than `ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /mattermost/data' returned a non-zero code: 4294967295` ?
I don't know Windows and I don't have anything to test it. Are you able to build the following basic Dockerfile on your server ? 
```
FROM debian:jessie

RUN mkdir /test
```

**Comment by gtaspider** [comment]
Hi,
Wow, your simple Dockerfile also throws an error, here is the complete output of the powershell:

> PS C:\docker\images\test> docker build -t mkdir-test .
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM debian:jessie
> jessie: Pulling from library/debian
> f2b6b4884fc8: Pull complete
> Digest: sha256:44d53bda18cc6b564cedca4bd4d7cfacce37a3f43a439ea8a73c4d8c32f53400
> Status: Downloaded newer image for debian:jessie
>  ---> 5dd74d62fab8
> Step 2/2 : RUN mkdir /test
>  ---> Running in 7adf1e9e12ed
> The command '/bin/sh -c mkdir /test' returned a non-zero code: 4294967295

So its not Mattermost related, I will post that in the docker github. If anyone has an Idea anyways I would be very pleased :)
Thanks,
Spider
