### ISSUE TITLE
exec in /bin/bash for docker-prod-app

### ISSUE THREAD

**Issue by gnubyte** [mattermost/mattermost-docker#253]
Really pushing my own knowledge and limits here, so this is likely a problem between the chair and keyboard, but I would like to execute a new shell session and attach my console to it for the prod app so I can get at some of the configs from server side. If there is a better process for this, call me a noob and offer up that better process...

When executing:
`docker exec -t -i mattermostdocker-app-1 /bin/bash`

I receive the error:
`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown`

This indicates to me that the base image does not contain a distribution flavor that would lend itself to having bash available... any input is appreciated.

**Comment by gnubyte** [comment]
Adding footnotes, found a thread with a similar issue here where it looks like the image was from scratch.

Where this is a production app I would assume that this may be from scratch to define security policies individually rather than inheriting another images implied security.
https://github.com/moby/moby/issues/5135

**Comment by gnubyte** [comment]
# 🤦‍♂️
Got it... problem between chair and keyboard. This can be marked as closed... I figured if bash wasn't available, shell would be.
Confirmation of the solution here for anyone else who gets stuck on this:

https://stackoverflow.com/questions/27959011/why-does-docker-say-it-cant-execute-bash

**Comment by pichouk** [comment]
Hi :)
Yep you got it, Bash is not installed because we are [based on Alpine image](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile).
FYI you can directly use `docker exec -it <your-mattermost-container-name> platform version` (as describe is [this doc](https://docs.mattermost.com/administration/command-line-tools.html#using-the-cli)) to manage your mattermost server.
