### ISSUE TITLE
Failure to attach a file bigger than 50mb

### ISSUE THREAD

**Issue by bijairimi** [mattermost/mattermost-docker#256]
#### Summary
I am running mattermost docker and I have issues while attaching big files i.e. bigger than 50mb. Both the desktop client and the browser keep displaying the progress icon. It hangs there until you refresh the browser.

![mattermost-big-file-upload-error](https://user-images.githubusercontent.com/22500475/38611270-8832ea82-3d83-11e8-8a73-51a3325c1bb0.png)

The ```docker-compose logs``` gives this:

```app_1  | [2018/04/11 12:17:19 CEST] [EROR] /api/v4/logs:client code=0 rid=7hwegrc7otdoiqd3ckwtcj3g9r uid=78g6orkr5fngbf8ggfcx3zn97e ip=172.18.0.1 msg: TypeError: n is not a function row: 1 col: 508188 stack: TypeError: n is not a function url: https://mattermost.---.com/static/0.a0ad48042e48bd6fc703.js [details: ]```

As written on the documentation page https://docs.mattermost.com/help/messaging/attaching-files.html

The Maximum File Size parameter has been configured correctly (in the example below I set the size limit to 500mb)

![mattermost-file-size](https://user-images.githubusercontent.com/22500475/38611696-aab958d8-3d84-11e8-9629-0d20ed8ace18.png)

#### Steps to reproduce
Mattermost version: 4.8.1
- set the preferred Max Size Limit > 50mb
- try to send an attachment to other users or to a channel
- you will see that it hangs during the uploading process.

**Comment by pichouk** [comment]
Hi !
Did you use the `web` Docker image ? Because the limitation is then set [by Nginx](https://github.com/mattermost/mattermost-docker/blob/master/web/mattermost#L27).  
You need to change both `client_max_body_size` value on the Dockerfile or (better) use you own and customized reverse proxy :)

**Comment by bijairimi** [comment]
Hi @pichouk,

Thanks for the guides, the issue is now solved by changing the value of ```client_max_body_size``` on both ```mattermost-docker/web/mattermost``` and ```mattermost-docker/web/mattermost-ssl```. Then I rerun ```docker-compose build``` and ```docker-compose up -d```.

Thank you.
