### ISSUE TITLE
4.8.0 to 4.9.0 upgrade issue (port 8000)

### ISSUE THREAD

**Issue by fculpo** [mattermost/mattermost-docker#259]
Doc should maybe specify that some settings changed in the official production Docker image, especially the exposed port that is now 8000 instead of 80.

I had to reconfigure reverse proxy and config.json to adapt this setting (ListenAddress).

First release in quite some time that did not simply worked with `docker pull mattermost/mattermost-prod-app:4.9.0 &&  docker pull mattermost/mattermost-prod-db:4.9.0 && docker-compose down && docker-compose up -d`

**Comment by pichouk** [comment]
I'm sorry about that, it seems that it cause more troubles than expected. In fact I write down some [release notes](https://github.com/mattermost/mattermost-docker/releases/tag/4.9.0) on this Github repository + posted [a message](https://pre-release.mattermost.com/core/pl/x1r9piahntgx8edoi4xan81sxy) on the Mattermost community server.

First, maybe it was not the best way to notify users and maybe, in the future, I should also add an entry to the official [Mattermost changelog](https://docs.mattermost.com/administration/changelog.html) (ping @jasonblais to discuss about a procedure for me to add information on this changelog).

Second our documentation is poor of information for users who want to use their own reverse-proxy (which is something [I want to encourage](https://github.com/mattermost/mattermost-docker/issues/245)). That's an issue, and we must work on it.

**Comment by jasonblais** [comment]
@pichouk What if we follow the Mattermost deprecation policy? https://docs.mattermost.com/process/deprecated-features.html

This would mean sufficient notice ahead of time + notes in changelog, important upgrade notes, etc. at the time of release. We should also consider following the [removal targe date guidelines](https://docs.mattermost.com/process/deprecated-features.html#removal-target-date).

Let me know your thoughts? If that sounds reasonable, perhaps you can help draft a description to our [changelog](https://docs.mattermost.com/administration/changelog.html) and [important upgrade notes](https://docs.mattermost.com/administration/important-upgrade-notes.html) that affected v4.9 release? It can be short with a link to a more detailed release note in the GitHub repository. I can help with it of course too.

**Comment by fculpo** [comment]
fine for me, this can be closed

**Comment by pichouk** [comment]
Short notice to everyone who's read this issue : we are working on a better way to warn users when there is changes that required some extra steps to upgrade.  
For this time, my bad I'm sorry. I just added some notes also on the README file which seems to be more read than the Github release notes. We will also probably add some notes on the Mattermost official changelog.
