### ISSUE TITLE
Install on Red Hat Enterprise Linux Server release 7.2 (Maipo)

### ISSUE THREAD

**Issue by yboussard** [mattermost/mattermost-docker#26]
docker : Docker version 1.11.2, build b9f10c9
docker-compose:  docker-compose version 1.7.1, build 0a9ab35

After docker-compose up -d 

mattermostdocker_db    is     Exited

And docker start -i mattermostdocker_db_1 give

[docker@localhost mattermost-docker]$ docker start -i mattermostdocker_db_1
AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: could not access directory "/var/lib/postgresql/data": Permission denied
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

**The same error is present on os x installation** 
os x el capitan : 15.0.0 Darwin Kernel Version 15.0.0
Docker version 1.11.1, build 5604cbe
docker-compose version 1.7.1, build 0a9ab35

**Comment by yboussard** [comment]
For information:
with 
docker version 1.9.1, build a34a1d5
docker-compose version 1.6.2, build 4d72027
CentOS Linux release 7.2.1511 (Core) 

All container are running and there is no error with docker-compose.

**Comment by npcode** [comment]
The problem on installation on CentOS seems a duplication of #24 and osx case is duplication of #6.

**Comment by jasonblais** [comment]
Thanks very much @yboussard for the report,

Can you help confirm your report is covered by issues [#24](https://github.com/mattermost/mattermost-docker/issues/24) (installation on CentOS) and [#6](https://github.com/mattermost/mattermost-docker/issues/6) (installation on OSX)?

**Comment by lfbrock** [comment]
Going to close this issue as a duplicate, please re-open if it is a separate issue.
