### ISSUE TITLE
4.7.1 to 4.9.0 - Permission Denied

### ISSUE THREAD

**Issue by bgualda** [mattermost/mattermost-docker#260]
Hi guys,
I realized docker upgrade from 4.7.1 to 4.9.0 following the proceeding, but when I make the start in docker-compose.sh, the app images can't start.
What's the problem ?
Look:

Using existing config file /mattermost/config/config.json
Configure database connection...OK
Wait until database db:5432 is ready...
Starting platform
FileLogWriter("/mattermost/logs/mattermost.log"): open /mattermost/logs/mattermost.log: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9aedfc]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go.(*FileLogWriter).SetFormat(...)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go/filelog.go:199
github.com/mattermost/mattermost-server/utils.ConfigureLog(0xc420171f98)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/utils/config.go:126 +0x14c
github.com/mattermost/mattermost-server/app.(*App).LoadConfig(0xc4201e4240, 0x13f6bce, 0xb, 0xc4201e4240)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/config.go:56 +0x133
github.com/mattermost/mattermost-server/app.New(0xc4201f49f8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/app.go:133 +0x486
github.com/mattermost/mattermost-server/cmd/commands.runServer(0x13f6bce, 0xb, 0xc4200fe400, 0xc4200fe4e0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:62 +0xe9
github.com/mattermost/mattermost-server/cmd/commands.serverCmdF(0x24800c0, 0x24ba100, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:53 +0x10d
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x24800c0, 0xc420010180, 0x0, 0x0, 0x24800c0, 0xc420010180)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:753 +0x475
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24800c0, 0x24ba100, 0xc42004bf40, 0x10f863c)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x24800c0, 0x0, 0xc42004bf40)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/mattermost/mattermost-server/cmd.Run(0xc420010180, 0x0, 0x0, 0xc42004bf70, 0x1109719)
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/cmd.go:14 +0x6d
main.main()
	/var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/main.go:33 +0x63

**Comment by spinanicky** [comment]
View the readme: 
mkdir -p ./volumes/app/mattermost/{data,logs,config}
chown -R 2000:2000 ./volumes/app/mattermost/
docker-compose start

**Comment by bgualda** [comment]
OMG !!!
This is my mistake.
Thank you spinanicky.
