### ISSUE TITLE
Can't start app service: can't create /mattermost/config/config.json.tmp: Permission denied

### ISSUE THREAD

**Issue by stepankuzmin** [mattermost/mattermost-docker#262]
app service couldn't be started because of permission issues:

```shell
app_1  | No configuration file /mattermost/config/config.json
app_1  | Creating a new one
app_1  | cp: can't create '/mattermost/config/config.json': Permission denied
app_1  | /entrypoint.sh: line 81: can't create /mattermost/config/config.json.tmp: Permission denied
```

Ubuntu 16.04
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.21.0, build 5920eb0

macOS
Docker version 18.03.0-ce build 0520e24
docker-compose version 1.20.1, build 5d8c71b

mattermost-docker https://github.com/mattermost/mattermost-docker/commit/c92df51d68212816495501c039938eb11aa34d25

Steps to reproduce:

```shell
git clone https://github.com/mattermost/mattermost-docker.git
cd mattermost-docker
docker-compose build
docker-compose up -d
```

**P.S.** adding `edition=team`, `PUID` and `PGID` build args has no effect

**Comment by pichouk** [comment]
Did you setup the correct access rights for your volumes [as described in the README](https://github.com/mattermost/mattermost-docker#start) ?

**Comment by pichouk** [comment]
What is the result of `ls -la ./volumes` ?

**Comment by stepankuzmin** [comment]
Thanks for reply! Chowning volumes fixed that.

**Comment by tawalaya** [comment]
Hi, I also encountered this problem and followed all the steps described in the documentation. Upon further investigation, I found out that the problem was due to SElinux. See this [issue](https://github.com/moby/moby/issues/24508) with ultimately helped me resolve the problem.

**Comment by Docteur-RS** [comment]
`sudo setenforce 0` did the trick (until next reboot at least)

**Comment by l3lackcurtains** [comment]
Fixed this error by
```bash
chown $USER:$USER ./volumes
```
