### ISSUE TITLE
SSL/TLS web container configuration for 4.9.0 broken?

### ISSUE THREAD

**Issue by daydr3am3r** [mattermost/mattermost-docker#263]
Greetings!

As documented in the 4.9.0 changes, the app container was moved to listen to a non-privileged port (8000 instead of 80). While upgrading my setup from 4.8.1, I noticed that SSL/TLS forwarding from the web reverse proxy towards the app stopped working. No matter what I tried [1], the requests kept being forwarded to port 80 instead of port 8000. As 443 is also a privileged user port, I was wondering what the new port in use should be.

Is `docker-compose.yml` updated to reflect a redirection to a new non-privileged SSL/TLS port?

There's a good chance I did something wrong, but if this a feature and not a bug, the documentation probably has to be updated to clarify the new behavior. I personally ended up setting up my own nginx reverse proxy instead.

[1] Things I tried:
- configuring `443:8000` in `docker-compose.yml`
- setting `-MATTERMOST_ENABLE_SSL = true`
- setting `APP_PORT_NUMBER=8000` and `APP_HOST=http://app` as an environment variable
- setting only `APP_PORT_NUMBER=8000` as an environment variable

**Comment by daydr3am3r** [comment]
To simplify the issue, there are two questions with regards to: 

1. `config.json`:  If the standard port got shifted from 80 to 8000 in 4.9.0, where was the standard TLS port shifted to? Is this also configurable in `config.json` and where exactly? Is this documented someplace?
2. `docker-compose.yml`: The documentation mentions that `docker-compose.yml` needs to be updated for port 80 to 8000, but it doesn't say anything about TLS connectivity, so it's not clear if something needs to be updated there, and what that is.

Thanks for providing pointers @tumbl3w33d, as stated I already worked around it but still feel that, at minimum documentation, could be better around this change.

**Comment by pichouk** [comment]
@daydr3am3r Are you using the `web` docker image ? Because if yes, you don't have to change the TLS port. The `web` container is listening on port `80` and `443`, terminate TLS, and forward everything on the port `8000` of the `app` container.

If your are no using the `web` docker image, then your reverse-proxy need to forward request to port `8000` of your `app` container. But the `app` docker image is not supposed to support direct TLS.

**Comment by pichouk** [comment]
Hi @daydr3am3r,

did you manage to solve your issue ?

**Comment by daydr3am3r** [comment]
Hi Kyâne,<mailto:notifications@github.com>

The way I managed to solve it is to stop using the docker web proxy image and install an nginx reverse proxy in my server.



Kyâne Pichou<mailto:notifications@github.com>
2 June 2018 at 11:35

Hi @daydr3am3r<https://github.com/daydr3am3r>,

did you manage to solve your issue ?
