### ISSUE TITLE
Plugins: Enable Uploads options not available

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-docker#265]
In System Console > Plugins (Beta) > Configuration I only get option for enabling plugins, and not for enabling plugin uploads. 

I tried turning plugins off, restarting, turning it on and restarting again but it didn't work. I tried updating config.json directly but it still doesn't work. The plugins section of my config.json looks like this -

```
"PluginSettings": {
        "Enable": true,
        "EnableUploads": true,
        "Directory": "./plugins",
        "ClientDirectory": "./client/plugins",
        "Plugins": {},
        "PluginStates": {}
    }
```

I referenced to https://forum.mattermost.org/t/mattermost-plugins-in-beta/4123/14 but the fix for working directory is allready applied and released in the docker build version 4.9.1.

**System information:**
**OS:** Ubuntu 18.04
**Docker:** Docker version 18.03.1-ce, build 9ee9f40
**Go:** go version go1.10.1 linux/amd64

**Comment by pichouk** [comment]
I'm using a `4.9.0` server and if I enable plugin I have the option to upload. I'll try later (don't have access right now) to upgrade to `4.9.1` and check if I have the same issue.

**Comment by pichouk** [comment]
I just try with Mattermost `4.9.1` and now I have the same issue than you.
Since it seems to be a Mattermost issue more than a Docker image issue, and because you opened an issue on `mattermost-server` repository, I close this ticket. If it happen that it is only an issue on Docker install, feel free to re-open :)
