### ISSUE TITLE
Bootstrapping new mattermost-docker does not work

### ISSUE THREAD

**Issue by compilenix** [mattermost/mattermost-docker#272]
I've followed the instructions described at [Production Docker Setup on Ubuntu](https://docs.mattermost.com/install/prod-docker.html#production-docker-setup-on-ubuntu) exactly on a current / fresh install of ubuntu 18.04  server and get "stuck" right after the `docker-compose up -d` command.
The containers are running and a `curl http://localhost/` returns `502 Bad Gateway`

The folder `volumes/app/mattermost/logs` is empty.
Could you help me and which useful informations can i provide?

Grateful,
CompileNix

**Comment by pichouk** [comment]
Hi @compilenix.
I'm sorry, it seems that this documentation page is not up to date. I will not be able to fix it before next weeks, but to unblock you, I invite you to check at the README especially [the part about UID/GID](https://github.com/mattermost/mattermost-docker#start) which may be your problem.

**Comment by amyblais** [comment]
Hi @pichouk! The doc PR mentioned by @compilenix is ready for final dev review: https://github.com/mattermost/docs/pull/2027

**Comment by pichouk** [comment]
Hi @amyblais, I answered on the PR. It's perfect :ok_hand:
