### ISSUE TITLE
Cannot connect to the server in mobile app after update to 4.10.0

### ISSUE THREAD

**Issue by vukhanhtruong** [mattermost/mattermost-docker#276]
Hi, 

Everything works fine after upgrading, but the mobile app.
Also, the logs section in the console, it shows nothing.
Please give me your advice.
Thank you so much for your great work.

**Comment by pichouk** [comment]
Hi,

I have no issues with my mobile application with my MM `4.10.0` server. Are you using the [last version](https://github.com/mattermost/mattermost-mobile/releases) of the mobile application ?  
However, I don't think it is a Docker issue, maybe you should open an issue on the `mattermost-mobile` repository if you still have this issue after upgrade.

**Comment by vukhanhtruong** [comment]
ok thanks for your support.
