### ISSUE TITLE
mattermost app Dockerfile fails to pull application

### ISSUE THREAD

**Issue by skyleronken** [mattermost/mattermost-docker#277]
I have been trying to get a team edition stood up and running. DB and Web are apparently find, but App keeps restarting. The logs indicate an issue with locating the config. I manually created the volume directory with its necessary subdirectoris. There is no json file within the config directory. When I look at the Dockerfile and the entrypoint it looks like the container is failing to pull down the Mattermost app. I won't claim to be any sort of docker expert, so any sort of help is appreciated.

**Comment by pichouk** [comment]
Hi, do you have the specific log error please ? If there is no configuration file, the entrypoint should should a default one, we should find why it doesn't :)
