### ISSUE TITLE
Hope mattermost-prod-db can support chinese full text search

### ISSUE THREAD

**Issue by daoleno** [mattermost/mattermost-docker#279]
DB source image become  postgres-alphine, some instruction in doc can not work.Hope default CJK can be supported.

https://docs.mattermost.com/install/i18n.html#chinese

**Comment by pichouk** [comment]
Hi @daoleno :)

Thanks for your report ! I'm really sorry if we break database for some languages...
I don't understand the documentation page (I don't speak this language). Are you able to describe what are the operation describe on documentation ? And/or do you have a specific error when you try to do those operations ?

**Comment by daoleno** [comment]
Hi @pichouk 

Mattermost can not search Chinese in [some case](https://github.com/mattermost/mattermost-server/issues/2033#issuecomment-182336690).That doc describe how to add Chinese search feature in postgresql.  Before i just add a new layer with this feature on your docker image, but now new alphine image have not some apt package like postgresql-server-dev-9.3, so it was broken.
It's an extended feature.Actually the feature have a bug that will search in all channel.So it just apply to some special case.

**Comment by daoleno** [comment]
And there is another case.

Our volume is mounted in a busybox platform.The previous file permission is root, now it be changed to mattermost, when i upgrade from 4.6 to 4.10, all file feature was broken, including file upload, user avatar, etc... So i  changed the file permissions.
Maybe this will affect some others. Just mention it.

**Comment by pichouk** [comment]
Hum OK, can you tell me the list of packages you were using on previous image ? Maybe we can find a replacement (for example it seems that a `postgresql-dev` package [exists](https://pkgs.alpinelinux.org/packages?name=postgresql-dev-9&branch=v3.7) on Alpine). If not you should probably use another database image.

**Comment by daoleno** [comment]
The list of packages
```
wget gcc make bzip2 postgresql-server-dev-9.4 libpq-dev 
```

**Comment by pichouk** [comment]
I'm trying to find a solution to install Postgresql dev files inside the database container, but I don't know how. Maybe you should use another database image for this specific use...

**Comment by daoleno** [comment]
OK.I will try it.Thanks a lot.
