### ISSUE TITLE
Rename $DB_PORT_5432_TCP_PORT variable

### ISSUE THREAD

**Issue by auguster** [mattermost/mattermost-docker#28]
I just deployed a Mattermost docker container and I lost some time figuring out why the container wasn't connecting to the DB. I used `DB_PORT` instead of unintuitive `DB_PORT_5432_TCP_PORT` in my docker run.

I think this variable should be renamed to something user-friendly with less redundancy, why not `DB_PORT`, `DB_TCP_PORT` or `DB_PORT_TCP` ? In the `config.template.json` the replaced string is `DB_PORT` anyway.

Also, those variable should be displayed in the echo of `docker-entry.sh`
```
echo "Wait until database is ready..."
```
could be:
```
echo "Wait until database $DB_HOST:$DB_PORT_5432_TCP_PORT is ready..."
```
It would make error diagnose a lot easier ;)

**Comment by npcode** [comment]
Good point. [$DB_PORT_5432_TCP_PORT is a legacy from docker-compose version 1](https://docs.docker.com/compose/link-env-deprecated/) which is deprecated and we don't need to use it. I'll try to make it better.

**Comment by npcode** [comment]
Oops, we are still using docker-compose version 1.

We have used DB_PORT_5432_TCP_PORT instead of DB_PORT because what we want is only the port number, instead of the full url, to construct the url to the postgres db.
