### ISSUE TITLE
Cannot start app container. (standard_init_linux.go:190: exec user process caused "no such file or directory")

### ISSUE THREAD

**Issue by lyenliang** [mattermost/mattermost-docker#281]
I want to install `app`, and `web` services in one ubuntu 16.04 machine. And use my own AWS RDS as the Database. 

So I followed the tutorial [here](https://docs.mattermost.com/install/prod-docker.html#production-docker-setup-on-ubuntu) to setup.

The modifications I have made to the config files are as follows:

1. Change `DB_HOST`, `DB_PORT_NUMBER`, `MM_USERNAME`, `MM_PASSWORD`, and `MM_DBNAME` variables in `app/entrypoint.sh` so that I can connect to my AWS RDS.

2. Add 
`MM_SQLSETTINGS_DRIVERNAME=mysql` and 
`MM_SQLSETTINGS_DATASOURCE="${MM_USERNAME}:${MM_PASSWORD}@tcp(${DB_HOST}:${DB_PORT_NUMBER})/${MM_DBNAME}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"`
to line 16, and 17 at `app/entrypoint.sh`.

3. Uncomment out line 26 - line 29 in `docker-compose.yml` to install team edition.

4. Comment out `db` service in `docker-compose.yml` because I have my own database.

5. Set `MM_USERNAME`, `MM_PASSWORD`, and `MM_DBNAME` the same as that of my AWS RDS.

When I run `docker-compose up -d`, I found a `standard_init_linux.go:190: exec user process caused "no such file or directory"` error inside the `app` container. I found this error message by using `docker logs -f <app_container_id>`.

Is there anything wrong with my configuration?

**Comment by jstdoit** [comment]
so please, how did you solve this problem?
