### ISSUE TITLE
Bad Request from NGINX after upgrade to 5.0.0

### ISSUE THREAD

**Issue by felipeborgez** [mattermost/mattermost-docker#286]
Hi everyone!
I tried to upgrade Mattermost to 5.0.0 version but ngnix returns 502 Bad Gateway only.

The app service returns follow messages: 
![mattermost error](https://user-images.githubusercontent.com/4450268/42108990-7fc6844a-7bb2-11e8-8887-d15299776bb1.png)

I did a clean installation and it works.
I think that there is a relation with volumes folder permissions because I replaced the volumes folder of the clean installation and it shows the same error.

**Comment by pichouk** [comment]
Hi @felipeborgez :)
What was your previous version ? It seems that you need to follow upgrade process [described here](https://github.com/mattermost/mattermost-docker#upgrading-mattermost-to-49) that is required for versions previous than `4.9.0`

**Comment by felipeborgez** [comment]
Hi @pichouk !
This is the problem! I forgot to check my previous version.
I did volume folder backup only before upgrade.
I tried many oldest version but it didn't work.

After upgrade, I followed this upgrade process to 4.9+ with a volumes backup copy but didn't work too.

**Comment by pichouk** [comment]
Can you provide output of `ls -la ./volumes/app/mattermost/` please ? And also of `cat ./volumes/app/mattermost/config/config.json | grep ListenAddress` ?
It really seems to be an issue with file permissions and port binding.

**Comment by felipeborgez** [comment]
@pichouk I'm sorry!
I put a wrong number to ListenAddress.
My server is working now!

Thank you!

Can I close this issue?

**Comment by pichouk** [comment]
It's ok, problem solved that's what "matters most" :stuck_out_tongue:
