### ISSUE TITLE
Making default app port 8000 configurable?

### ISSUE THREAD

**Issue by lyenliang** [mattermost/mattermost-docker#288]
Do you think that configuring the default `app` container port (which is 8000) through `docker-compose.yml` is a good idea?

I have an [issue](https://stackoverflow.com/questions/51237711/docker-compose-crating-multiple-set-of-services/51256554?noredirect=1#comment89530846_51256554) where I want to create multiple set of mattermost services. 

That is the reason I want to configure the default port of `app` through `docker-compose.yml` file.

I would like to create a pull request to implement this feature if I got positive feedbacks from the discussion here.

**Comment by pichouk** [comment]
Hi :)
Why do you want to change the port used by the Mattermost application ? You can have 3 mattermost application containers, listening on their port 8000. You just need to ask your web servers to use the correct container.
