### ISSUE TITLE
Use mattermost 5.1.0 image

### ISSUE THREAD

**Issue by pgold30** [mattermost/mattermost-docker#291]
Support for latest image mattermost/mattermost-prod-app:5.1.0
view changelog for more info

**Comment by pichouk** [comment]
I don't understand, this Mattermost version should be [already supported](https://github.com/mattermost/mattermost-docker/releases/tag/5.1.0)

**Comment by cpanato** [comment]
closing this issue. The tag is already published

**Comment by pgold30** [comment]
Its refred to the kubernetes version which ios 4.7 https://github.com/mattermost/mattermost-docker/tree/master/contrib/kubernetes

**Comment by pichouk** [comment]
Ok I understand. I didn't test images on Kubernetes. If you try to change the tag ob [this file](https://github.com/mattermost/mattermost-docker/blob/master/contrib/kubernetes/mattermost.deployment.yaml#L20) and check if it works on K8S, feel free to submit a PR :)

**Comment by cpanato** [comment]
it works because I use in my personal cluster. however we have a k8s image for both EE and TE

https://hub.docker.com/r/mattermost/mattermost-team-edition/
https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/
