### ISSUE TITLE
Update to 5.1.1

### ISSUE THREAD

**Issue by kratan** [mattermost/mattermost-docker#293]
Hi,
can you update to latest mattermost version (today 5.1.1) available on dockerhub?

https://hub.docker.com/r/mattermost/platform/tags/

Greets

**Comment by cpanato** [comment]
hello @kratan in this repository the tag `5.1.1` already exist: https://hub.docker.com/r/mattermost/platform/tags/

**Comment by kratan** [comment]
@cpanato : thanks for replying. 
sorry for confusing, https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile is still pointing to 5.1.0

greets

**Comment by cpanato** [comment]
@kratan this repo points to https://hub.docker.com/r/mattermost/mattermost-prod-app/

there is a PR in place when it gets merged the tag will be available.
https://github.com/mattermost/mattermost-docker/pull/294

**Comment by pichouk** [comment]
Thanks to @cpanato I added the new tag `5.1.1` on this repository. It should upgrade Docker Hub images.
