### ISSUE TITLE
Add Shell when want to access the MM-app

### ISSUE THREAD

**Issue by cpanato** [mattermost/mattermost-docker#299]
When you try to access the container it says there is no shell to interact. 
We should add the shell, so we can run the mattermost commands available 

cc @pichouk

**Comment by pichouk** [comment]
In fact you can run Mattermost commands easily with `docker exec` like this
```
$ docker exec -it mattermost-app mattermost version
Version: 5.0.0
Build Number: 5.0.0
Build Date: Fri Jun 15 15:20:31 UTC 2018
Build Hash: 85a75526c7c03fca1d14a39cfb3f2638d98d3fe1
Build Enterprise Ready: false
DB Version: 5.0.0
```
So I don't think we need a shell. But if you have a use case that seems legit, we can add `bash` into installed package (image will be bigger, but not that much I guess).

**Comment by cpanato** [comment]
ok, fair enough for now, thanks
