### ISSUE TITLE
Please publish the Dockerfile of mattermost-push-proxy

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost-docker#303]
The Dockerfile is not visible on https://hub.docker.com/r/mattermost/mattermost-push-proxy/
Please be more transparent and setup automated builds from GitHub for mattermost-push-proxy.

**Comment by cpanato** [comment]
Hello @J0WI 

The dockerfile for the push proxy you can found here: https://github.com/mattermost/mattermost-kubernetes/blob/master/docker/push-proxy/Dockerfile

**Comment by J0WI** [comment]
Thanks for the link! I wonder why there are multiple repos.
So how about automated builds for it?

**Comment by cpanato** [comment]
This repo have the same tags as the others. the build for push proxy is automated and is generated every time we publish a new release or a RC.

I will consolidate in future everything.

**Comment by J0WI** [comment]
I'm still confused.
https://github.com/mattermost/mattermost-push-proxy/releases shows 4.4.10 as latest version
https://hub.docker.com/r/mattermost/mattermost-push-proxy/tags/ has 4.4.13 and 5.2.1, but no `latest` tag

Furthermore, the container in https://github.com/mattermost/mattermost-push-proxy/ depends on an outdated Ubuntu whereas Alpine or Debian are more common

**Comment by cpanato** [comment]
there is no latest tag for now.

Are you interested in submitting a PR to fix the outdated Ubuntu? I'm happy to review and merge it.

**Comment by J0WI** [comment]
Do I need to sign your [CLA](https://www.mattermost.org/mattermost-contributor-agreement/) for this?

**Comment by cpanato** [comment]
yes

**Comment by J0WI** [comment]
Therefore [I can't](https://github.com/mattermost/docs/pull/1772#issuecomment-362914870) :cry:

**Comment by cpanato** [comment]
:/ almost all the CLAs require that information.

**Comment by J0WI** [comment]
Why have this issue been closed? The `mattermost-push-proxy` conatiner is still outdated. Should I open a more specific issue for this?

**Comment by pichouk** [comment]
I closed because it does not seems related to this repository. I don't know where the Dockerfile of `mattermost-push-proxy` should be (is [`mattermost/mattermost-kubernetes`](https://github.com/mattermost/mattermost-kubernetes/blob/master/docker/push-proxy/Dockerfile) the right place ?), but it is not in this repository.

**Comment by cpanato** [comment]
@J0WI the `mattermost-push-proxy` have the latest release as well `5.3.1`

**Comment by J0WI** [comment]
The latest release in https://github.com/mattermost/mattermost-push-proxy/releases is only `4.10.2`. Where does `5.3.1` come from? And the container still misses a `latest` tag.
Sadly there is no option to open issues in the other repos. Where should i report the [issues](https://github.com/mattermost/mattermost-docker/issues/303#issuecomment-417694736)?

**Comment by cpanato** [comment]
there are no code changes in the push proxy repository @J0WI so you can use that release. for issues, you can open in the push proxy repo.

the docker image for 5.3.1 should be the same for 5.3.0 and for 4.10.1
