### ISSUE TITLE
Update Alpine base

### ISSUE THREAD

**Issue by J0WI** [mattermost/mattermost-docker#304]
These are both based to an outdated version of the upstream image:
https://github.com/mattermost/mattermost-docker/blob/17b9055ed66d03361939cf88fb1f44da498880b6/app/Dockerfile#L1
https://github.com/mattermost/mattermost-docker/blob/17b9055ed66d03361939cf88fb1f44da498880b6/db/Dockerfile#L1

The web image is based on the latest tag:
https://github.com/mattermost/mattermost-docker/blob/17b9055ed66d03361939cf88fb1f44da498880b6/web/Dockerfile#L1
This might be suitable for Alpine and Postgres too (e.g. `postgres:9-alpine`).

**Comment by tejasbubane** [comment]
As far as I know, we cannot directly upgrade postgres: https://github.com/mattermost/mattermost-docker/issues/128

Other two are doable, but always keeping the latest version (ie. without a version number) has possibility of breaking things without knowing.

**Comment by tejasbubane** [comment]
Yes that is the app container. But in the issue you mention changing versions of all three containers - hence my comment that it will break things for postgres version upgrade from 9x to 10x.

I guess you can go ahead and create a PR for upgrading `app` and `web` containers. That should not cause any issues.

**Comment by J0WI** [comment]
Sadly I can't provide a PR myself due the [CLA issue](https://github.com/mattermost/docs/pull/1772#issuecomment-362914870).
But the patch would be fairly easy, feel free to use it:
```patch
diff --git a/app/Dockerfile b/app/Dockerfile
index 462f9f3..2a8f6cb 100644
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,4 +1,4 @@
-FROM alpine:3.6
+FROM alpine:3.8
 
 # Some ENV variables
 ENV PATH="/mattermost/bin:${PATH}"

```
