### ISSUE TITLE
Backup to S3 Failure

### ISSUE THREAD

**Issue by cobenash** [mattermost/mattermost-docker#319]
Hey Guys

Does anybody face the same situation?

I got the following error message when I used the command

`docker exec mattermost-db su - postgres sh -c "/usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-push /var/lib/postgresql/data"`

`Traceback (most recent call last):
  File "/usr/bin/wal-e", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=2.1.4' distribution was not found and is required by azure-keyvault
LOG:  archive command failed with exit code 1
DETAIL:  The failed archive command was: /usr/bin/wal-e wal-push pg_xlog/000000010000077D00000026
LOG:  incomplete startup packet
ERROR:  relation "idx_teams_description" does not exist`

Does anybody can help me ?

**Comment by cobenash** [comment]
I found out maybe the main reason is as below
`envdir '/etc/wal-e.d/env' does not exist`

**Comment by cobenash** [comment]
I found out the problems. When I pull the latest postgres:9.4-alpine, the error message `Traceback (most recent call last): File "/usr/bin/wal-e", line 6, in <module> from pkg_resources import load_entry_point File ...` was gone.

I think the remain problem is that /etc/wal-e.d/env does not exit.

**Comment by pichouk** [comment]
I really don't know how this part (S3 backup) works. What is this `/etc/wal-e.d/env` file ?

**Comment by cobenash** [comment]
@pichouk /etc/wal-e.d/env is a folder created by envdir.
we can use this envdir plugin to store the S3 environment variables.

you can see the code belowed, and it was written in wal-e official github page: https://github.com/wal-e/wal-e

`
# Assumption: the group is trusted to read secret information
# S3 Setup
$ umask u=rwx,g=rx,o=
$ mkdir -p /etc/wal-e.d/env
$ echo "secret-key-content" > /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
$ echo "access-key" > /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
$ echo 's3://some-bucket/directory/or/whatever' > \
  /etc/wal-e.d/env/WALE_S3_PREFIX
$ chown -R root:postgres /etc/wal-e.d

`
we can use backup command only with this settings, but it is disappeared now.

On the other hand, I think we need to change the backup command to
`docker exec mattermost-db su - postgres sh -c "/usr/bin/envdir /etc/wal-e.d/env /usr/bin/wal-e backup-push /var/lib/postgresql/data"`

because the path of wal-e has been changed from `/usr/local/bin/wal-e` to `/usr/bin/wal-e`

Does anybody can confirm this again?

Thanks.

**Comment by cobenash** [comment]
Fixed at #324 PR.
