### ISSUE TITLE
FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by gregorifaroux** [mattermost/mattermost-docker#325]
When trying to do a fresh install of mattermost-docker (after a git clone https://github.com/mattermost/mattermost-docker.git), I receive a `FATAL:  role "root" does not exist` during the docker-compose up.

Any suggestions on how to correct the issue? Thanks. I am trying on a Mac OS 10.14.

**Comment by pichouk** [comment]
This is the same message that issue #313 and I though I fixed it with PR #318 ...

In fact if I remove the `HEALTHCHECK` directive from the Dockerfile, I have the same error message as you. So I don't know what it is...

**Comment by pichouk** [comment]
Correct, if I create a brand new Mattermost server (removing all data from volumes) **without** the database `HEALTHCHECK` I don't have this message.

It seems that it doesn't break anything, but `pg_isready` don't use the correct user to test database connection. I'll try to see if I can fix that.

**Comment by pichouk** [comment]
It should be fixed by #330

**Comment by alejorojas** [comment]
Hi! If I leave this line like this:

HEALTHCHECK CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1

I get **role "mattermost" does not exist**

If I leave like this:

HEALTHCHECK CMD pg_isready || exit 1

I get **role "root" does not exist**

Any help?
