### ISSUE TITLE
Can't create team with release 5.4.0

### ISSUE THREAD

**Issue by aijanai** [mattermost/mattermost-docker#329]
Hi,

In 5.3.1 I can create a new team upon bootstrapping via docker-compose.

In 5.4.0, after creating the first user, the clickable string "Create a new team" is missing from the panel by which you join a team

**Comment by pichouk** [comment]
Do you have any error message ? I just try to spawn a new Mattermost instance locally, create a new team and it works correctly. After creating the team, I'm redirect to the Team chat interface.
