### ISSUE TITLE
Migrating from Slack using the Mattermost CLI

### ISSUE THREAD

**Issue by EdHarkin** [mattermost/mattermost-docker#336]
Hi,
I was wondering if someone can help me. I'm trying to import a slack export using the following command:

docker exec -it mattermostdocker_app_1 mattermost import slack team_name /mattermost/config/slack_team.zip

It returns the following message, but nothing gets imported. Any suggestions?
Thank you

> Mattermost Slack Import Log
> 
> Users created:
> ===============
> 
> The Integration/Slack Bot user with email slackimportuser_obfuscated@localhost and password obfuscated has been imported.
> 
> Channels added:
> =================
> 
> 
> Notes:
> =======
> 
> - Some messages may not have been imported because they were not supported by this importer.
> - Slack bot messages are currently not supported.
> - Additional errors may be found in the server logs.
> 
> 
> Finished Slack Import.

**Comment by pichouk** [comment]
I think this is more a trouble with the Slack importer than with the Docker image. You should try to get some help from the [Mattermost forum](https://forum.mattermost.org/) or on the [Mattermost repository](https://github.com/mattermost/mattermost-server) (for bug only).
