### ISSUE TITLE
Ubuntu doesn't work anymore

### ISSUE THREAD

**Issue by genotrance** [mattermost/mattermost-docker#337]
Your [docs](https://docs.mattermost.com/install/prod-docker.html#production-docker-setup-on-ubuntu) claim you can install on Ubuntu, there is no mention of Alpine anywhere.

However, you cannot install on Ubuntu since you switched to Alpine. Please update this somewhere, was a waste of time figuring it out.

**Comment by cpanato** [comment]
@genotrance I will review the doc and if need any update I will make it.

However, the documentation is related to install the Docker daemon in Ubuntu distribution. We are not installing the docker daemon in the alpine linux distribution.

We use alpine to build the Docker image which there is nothing related with ubuntu

**Comment by pichouk** [comment]
+1 @cpanato the documentation say that you can setup Docker on your Ubuntu (or whatever distribution actually) to deploy Mattermost. The fact that our Docker image is based on Alpine is not relevant here, but we can still add it inside the README.

**Comment by genotrance** [comment]
The production install documentation for Ubuntu 18.04 asks you to customize the image with passwords to make it more secure and then do a `docker-compose up -d` which builds the images. It gives you the impression that you can do it on Ubuntu for Ubuntu. However, each component has a Dockerfile which has `apk` commands in it which don't run on Ubuntu so you obviously cannot build.

If you have a way to run a production build on Ubuntu without building, I'm fine with that. Ideally, you can customize as well or its effectively the preview mode.

**Comment by pichouk** [comment]
I don't understand. To change your database password you just have to set [`POSTGRES_PASSWORD`](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml#L14) and [`MM_PASSWORD`](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml#L40) inside your `docker-compose.yml` file. It doesn't change anything if the image is based on Ubuntu or Alpine.

Also if you don't want to build your images, you can use those from [Docker Hub](https://hub.docker.com/u/mattermost/)

**Comment by cpanato** [comment]
you don't need to rebuild the docker image to pick your own password, just change the password for your own and run the image
