### ISSUE TITLE
DB health check results in postgres fatal log

### ISSUE THREAD

**Issue by tumbl3w33d** [mattermost/mattermost-docker#339]
The error message that shows up every 30 seconds in the postgres container log is
`FATAL:  role "-d" does not exist`

It doesn't seem to cause trouble and I guess it's a kind of health check on app side. Unfortunately, I don't know with which version of the container this started. Currently I'm running
```
Mattermost Version: 5.5.0
Database Schema Version: 5.5.0
Database: postgres
Build Hash: 826252252404c13bf564a8c4fd51616fc2cc4df9
EE Build Hash: 8eb31159c091f8a1e75c99ae6f4e47010dbf3731
Webapp Build Hash: 86bcb560c7dbd31967a28bf3b9da746da1a6947c
Build Date: Thu Nov 15 18:39:02 UTC 2018
```

**Comment by pichouk** [comment]
Hmm weird, should have been fixed by [this commit](https://github.com/mattermost/mattermost-docker/commit/94c09b61a01b36741bbaff283408a65bec7d6272)

**Comment by tumbl3w33d** [comment]
I think I figured out how that happened. I'm not using the docker-compose file that comes with the repo, but when I put that setup into my ansible deployment playbook, I kinda transferred it using the env vars that were used at that time.
These env vars were renamed at some [point in time](https://github.com/mattermost/mattermost-docker/commit/142b766cde2029cf0af88f47c0424dad30865428#diff-4e5e90c6228fd48698d074241c2ba760) and as a consequence the new ones are not set in my container.

I didn't have any issue with that because these envs were only relevant for a fresh db to initialize. My data is in a bind mount though, so I didn't notice until now. I'm fine with closing this since my setup might be exotic (i.e., not using the compose file). I leave it up to you if you wanna handle that condition.

**Comment by pichouk** [comment]
Ok, it explains your issue.
I'll close since there is nothing to fix here IMHO.
