### ISSUE TITLE
Support Let's Encrypt

### ISSUE THREAD

**Issue by micheljung** [mattermost/mattermost-docker#342]
Mattermost supports Let's Encrypt, but to enable it, the app must listen on Port 443. However, the stack is configured for port 8000 and changing this doesn't seen to be easy.

I added `libcap` to app/Dockerfile so I can allow listening on 443 using `RUN setcap CAP_NET_BIND_SERVICE=+eip /mattermost/bin/mattermost`
I tried modifying app/Dockerfile and export port 443 instead of 800,
I tried setting `APP_PORT_NUMBER=443` for the `web` service in docker-compose.yml

But in the `web` log, I still get:
```
web_1_31f82e97cfc4 | 2018/12/05 00:25:05 [error] 10#10: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:8000/", host: "localhost"
```
(It tries to access port 8000)

How to fix this?

**Update**
After removing/recreating the containers again, port 443 is now configured correctly. However, when accessing it either via healthcheck (https://localhost:443) or from outside (via domain), it still doesn't work.

App log is:
```
{"level":"info","ts":1543992431.7962077,"caller":"http/server.go:1763","msg":"http: TLS handshake error from 127.0.0.1:35880: acme/autocert: server name component count invalid","source":"httpserver"}
{"level":"info","ts":1543992433.3670666,"caller":"http/server.go:1763","msg":"http: TLS handshake error from 172.18.0.2:38624: tls: first record does not look like a TLS handshake","source":"httpserver"}
```

**Update2**
For some reason, `telnet localhost 80` works as well as `telnet <ip> 80`, also `telnet localhost 443` but not `telnet <ip> 443`. Even though:
```
tcp6       0      0 :::443                  :::*                    LISTEN      10391/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      10404/docker-proxy
```

**Comment by micheljung** [comment]
The way `web` and `app` were configured didnt't make sense. Now it works. What I did:

- Enable Let's Encrypt and Port 80 to 443 forwarding
- Let `app` expose ports 80 and 443 (configure in Dockerfile and in docker-compose.yml)
- Remove the `web` container because its only purpose was basically SSL, which is now handled by Mattermost

Profit!

**Comment by elcolie** [comment]
How did you make it through?

**Comment by elcolie** [comment]
I had tried your answer, but I can use `wss` #363
