### ISSUE TITLE
How backups work?

### ISSUE THREAD

**Issue by michaelr524** [mattermost/mattermost-docker#346]
I've setup the container with s3 access and it backs up wal-e segments to s3.
The README lacks an explanation how these backups work in general.
Is there a place where I can read more about it?
Specifically, the questions that I have right now are:

1. Is it enough to have these wal-e backups or do I need to also setup cron to run base backups?
2. Does the command to cleanup old base backups also cleans old wal-e segments? 
3. What is the procedure to restore?

**Comment by michaelr524** [comment]
Also, trying to run the base backup I get an error about the s3 prefix not specified. It's specified in the docker-compose.yml file. Should I specify it again separately somehow for the backup commands?

```
$ docker exec mattermost_db_1 su - postgres sh -c "/usr/bin/envdir /etc/wal-e.d/env /usr/bin/wal-e backup-push /var/lib/postgresql/data"
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-12-07T11:15:48.724757-00 pid=15905
wal_e.main   ERROR    MSG: no storage prefix defined
        HINT: Either set one of the --wabs-prefix or --s3-prefix options or define one of the WALE_WABS_PREFIX, WALE_S3_PREFIX, or WALE_SWIFT_PREFIX environment variables.
        STRUCTURED: time=2018-12-07T11:15:48.725017-00 pid=15905
```

**Comment by michaelr524** [comment]
I found a good explanation here: https://jbub.eu/2016/05/16/postgresql-backup-wale-cloud-files/
The db container exposes a volume for the wal-e environment variables (/etc/wal-e.d/env):
https://github.com/mattermost/mattermost-docker/blob/master/db/Dockerfile#L29

**Comment by michaelr524** [comment]
I made some progress, but there is a new problem now:

```
docker exec mattermost_db_1 su - postgres sh -c "/usr/bin/envdir /etc/wal-e.d/env /usr/bin/wal-e backup-push /var/lib/postgresql/data"
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-12-08T22:12:37.830561-00 pid=63
psql: FATAL:  role "postgres" does not exist
wal_e.main   ERROR    MSG: could not run one or more external programs WAL-E depends upon
        DETAIL: Could not get a connection to the database: note that superuser access
        is required
        Could not run the following programs, are they installed? psql, pv
        STRUCTURED: time=2018-12-08T22:12:37.871390-00 pid=63
```

**Comment by michaelr524** [comment]
Worked around the problem with this

```
docker exec -it mattermost_db_1  sh
psql -U mmuser mattermost
CREATE USER postgres SUPERUSER;
```

But now a new error:

```
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-12-08T23:04:32.337920-00 pid=1184
wal_e.main   ERROR    MSG: could not run one or more external programs WAL-E depends upon
        DETAIL: Could not run the following programs, are they installed? pv
        STRUCTURED: time=2018-12-08T23:04:32.375411-00 pid=1184
```

**Comment by michaelr524** [comment]
Added a new line with

`
pv \
`
here: https://github.com/mattermost/mattermost-docker/blob/master/db/Dockerfile#L14

Backup works now!

**Comment by ybudimirov** [comment]
Hi @michaelr524  
Thank you for details!

> 3. What is the procedure to restore?

Were you able find out how to restore?
