### ISSUE TITLE
Starting Nginx ln: failed to create symbolic link '/etc/nginx/sites-enabled/mattermost': File exists

### ISSUE THREAD

**Issue by tomtruitt** [mattermost/mattermost-docker#36]
can anyone tell me what is causing this?

**Comment by tomtruitt** [comment]
do i have to go into the container and remove this file? seems odd...

**Comment by tomtruitt** [comment]
actually i did go in a delete the file and restarted the container and the server runs but without ssl... so i suppose i need to edit that file? seems odd still

**Comment by tomtruitt** [comment]
yeah looked in the container and the defaults are there... not sure how this is supposed to work...

**Comment by tomtruitt** [comment]
ok so i modified the local mattermost-ssl file and even the mattermost file. i still got an error about certs files not being found... so i docker cp those files into the container and now it runs but i get a redirected to https but a bad gateway error...

**Comment by cybermachvi** [comment]
have you found a solution?
