### ISSUE TITLE
Propose features

### ISSUE THREAD

**Issue by elcolie** [mattermost/mattermost-docker#364]
I would like to propose a features
1. Caddy instead of `nginx + certbot`. You can just add one container on top of them

**Comment by pichouk** [comment]
We are an a path to probably drop support for `web` image (#245 #366). I let this issue in standby, but we will probably close it in the futur.

**Comment by elcolie** [comment]
After read the previous discussions so far. Looking forward to see the next release.
Thank you for your response.
