### ISSUE TITLE
How to enable logging?

### ISSUE THREAD

**Issue by Paxa** [mattermost/mattermost-docker#365]
How to enable logging without creating custom config?

Why need to disable `LogSettings.EnableConsole` ?
I think docker apps by default should print to stdout. It took me some time to understand that there was db connection error, because process just wait without saying anything

**Comment by Paxa** [comment]
Found solution:
```
        env:
          - name: MM_LOGSETTINGS_ENABLECONSOLE
            value: "true"
```

**Comment by pichouk** [comment]
Good point, I agree. Actually I did the same on my Mattermost instance
```
[...]
    "LogSettings": {
        "EnableConsole": true,
        "ConsoleLevel": "ERROR",
        "ConsoleJson": true,
[...]
```
I'll submit a PR about it.

**Comment by Paxa** [comment]
Thanks!
