### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by tomtruitt** [mattermost/mattermost-docker#37]
ok so i modified the host mattermost-ssl file and even the mattermost file. then `dc build` and `dc up -d` i still got an error about certs files not being found when inspecting the logs of the web container which stopped... so i `docker cp`'d those files into the container and now it runs and i even get redirected to https finally but see a bad gateway error from nginx

**Comment by tomtruitt** [comment]
I'm assuming both example.mattermost.com and yourdomain should be changed to my domain and the proxy http up address to be changed to the server IP right

**Comment by tomtruitt** [comment]
Ok using http://app:APP_PORT or whatever got it for me after manually docker container the files in place

**Comment by tomtruitt** [comment]
Maybe this should be documented or did I did I miss something somewhere that madee have to do it this way?

**Comment by tomtruitt** [comment]
nevermind totally my fault for not having fullchain.pem in the certs dir

**Comment by activedecay** [comment]
even with certs, i'm still getting 502
