### ISSUE TITLE
Add support for atmos/camo image proxy 

### ISSUE THREAD

**Issue by kratan** [mattermost/mattermost-docker#373]
Hi,
is it possible to have atmos/camo image proxy ready with mattermost?

see:

https://docs.mattermost.com/administration/image-proxy.html?highlight=image%20proxy

greets

**Comment by pichouk** [comment]
Hi,

I don't think this is the goal of this repository. We are currently [dropping support for `web` image](https://github.com/mattermost/mattermost-docker/pull/366) so I think we will not add more "side containers" like an image proxy.

**Comment by kratan** [comment]
Hi Pichouk,
thanks for your reply. I liked the All in One solution, I guess most ppl have a dedicated server for their mattermost installation. I suggested to include camo because currently i had problems with the builtin local image proxy in 5.8.

greets
