### ISSUE TITLE
docker-compose build ends in error for service 'db'

### ISSUE THREAD

**Issue by jby** [mattermost/mattermost-docker#378]
Result when running docker-compose build on macOS 10.14 using master:

```
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_pZbTV/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Ns4dll/install-record.txt --single-version-externally-managed --compile" failed with error code -9 in /tmp/pip-install-_pZbTV/gevent/
ERROR: Service 'db' failed to build: The command '/bin/sh -c apk add --no-cache       build-base       curl       libc6-compat       libffi-dev       linux-headers       python-dev       py-pip       py-cryptography     && pip --no-cache-dir install 'wal-e<1.0.0' envdir     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*' returned a non-zero code: 1
```

```
docker --version
Docker version 18.09.2, build 6247962
```
```
docker-compose --version
docker-compose version 1.23.2, build 1110ad01
```
What's wrong, and how can I solve it?

**Comment by pichouk** [comment]
It seems to be an error during the `gevent` installation (which is a dependency of `wal-e` or `envdir` I guess) but I cannot reproduce. Is that the only error log you have, because it doesn't give much information, maybe `pip` returned something else ?

**Comment by jby** [comment]
Aha, a more careful examination of the output gave this:
```
    byte-compiling /usr/lib/python2.7/site-packages/gevent/_socket3.py to _socket3.pyc
      File "/usr/lib/python2.7/site-packages/gevent/_socket3.py", line 222
        def makefile(self, mode="r", buffering=None, *,
                                                      ^
    SyntaxError: invalid syntax
```

**Comment by jby** [comment]
Found it, and pylint gives the same error:
```
pylint _socket3.py                                                                                                                                                                                                                                                                              [ruby-2.6.0]
No config file found, using default configuration
************* Module _socket3
E:222, 0: invalid syntax (<string>, line 222) (syntax-error)
```

**Comment by pichouk** [comment]
It's seems to be a problem on [gevent code](https://github.com/gevent/gevent/issues/601) but I don't understand why you have it, I cannot reproduce. They said on the issue that it's not a problem, is that blocking your build ?

**Comment by jby** [comment]
Very much blocking my build, yes. It bails out there and wont go further...

**Comment by jby** [comment]
Ok, tried it again today - and it seems to have built everything this time...
I'm at home with the flu, and shouldn't be doing this right now, will look into it more when back in the office.

**Comment by jby** [comment]
It _might_ have been a low memory issue, I increased the default amount of memory for the containers for another reason and that would have affected the one where I tried to build Mattermost as well.
