### ISSUE TITLE
how do i build fresh?

### ISSUE THREAD

**Issue by tomtruitt** [mattermost/mattermost-docker#38]
when i build and up -d i still wind up with same teams and users

**Comment by npcode** [comment]
All of the data are stored in the volumes `app` and `db` mounts. Delete all of them and containers then restart it again. See https://github.com/mattermost/mattermost-docker#removing.

**Comment by tomtruitt** [comment]
ok i did see that but was worried i was deleting something critical to at first i didn't realize it was just the mount point.. ok thank you again i think i'm good with this from here on out.
