### ISSUE TITLE
Mattermost 4.10.7 not start

### ISSUE THREAD

**Issue by ivanmpk** [mattermost/mattermost-docker#381]
Hi I tried install v4.10.7 with docker but get the folllow message: 

./docker-entry.sh: line 18: /mm/mattermost/bin/mattermost: No such file or directory

If I use tag latest work but I need use v4.x.x.

**Comment by pichouk** [comment]
I don't see a `4.10.7` tag in this repository, how do you run build your image ? I assume you just changed the [`MM_VERSION`](https://github.com/mattermost/mattermost-docker/blob/master/app/Dockerfile#L5) but from the `master` branch. The binary used to run Mattermost changed from `platform` to `mattermost`, I think this is your problem here.

My suggestion is to do the following : 
```
git checkout 4.10.1
sed -i "s/4.10.1/4.10.7/g" app/Dockerfile
docker-compose build
```

**Comment by cpanato** [comment]
I can rebuild the image

**Comment by cpanato** [comment]
I also can use 4.10.8

**Comment by cpanato** [comment]
ok, created a branch based on 4.10.0 and did the whole upgrades and tags for that. I will apply the same for the other versions as well

**Comment by cpanato** [comment]
@ivanmpk please use the latest 4.10.8 this contains some fixes for version 4.10

**Comment by cpanato** [comment]
let me know if works then we close this issue

**Comment by ivanmpk** [comment]
Hi, I tried with git clone -b v4.10 https://github.com/mattermost/mattermost-docker.git
But the app container status is "Restarting", and get the follow logs:

`No configuration file /mattermost/config/config.json
Creating a new one
cp: can't create '/mattermost/config/config.json': Permission denied
/entrypoint.sh: line 38: can't create /mattermost/config/config.json.tmp: Permission denied`

**Comment by pichouk** [comment]
I guess you forgot [this part](https://github.com/mattermost/mattermost-docker#start)
```
mkdir -p ./volumes/app/mattermost/{data,logs,config,plugins}
chown -R 2000:2000 ./volumes/app/mattermost/
```

**Comment by ivanmpk** [comment]
Sorry, I miss execute create directory. Now it's works. Thanks!

**Comment by flavienbwk** [comment]
> I guess you forgot [this part](https://github.com/mattermost/mattermost-docker#start)
> 
> ```
> mkdir -p ./volumes/app/mattermost/{data,logs,config,plugins}
> chown -R 2000:2000 ./volumes/app/mattermost/
> ```

Doesn't work for me.
