### ISSUE TITLE
Postgres Query using only single core CPU

### ISSUE THREAD

**Issue by EagleEnergy** [mattermost/mattermost-docker#382]
Hi,

I have perfom a migration of my mattermost from VM environment to docker-compose stack.

First look appear like good, I recover all my testsing channels, users with personnal avatars,  custom emoji,...., anythings!

But the search is broken.

I have research a few of words and results is always nothing...

I don't know what I need to do.

Maybe rebuild an indexation table ?

**Comment by EagleEnergy** [comment]
I found the problem is due of timeout, I have increase the query timeout to 600s and know the search is OK. 

All my request take average of 40s to finish, it's feel too long. My CPU is 100% use in 1Core during query.

It's possible to make it more efficient ?

**Comment by pichouk** [comment]
I don't know, are you using the same server than before ? I don't see why the Docker deployment induce such an overhead in CPU usage.

**Comment by EagleEnergy** [comment]
Sorry I don't see your answer @pichouk.
No I don't use the same server, I use a smaller. 

This is why 1 core is now not enough.

**Comment by pichouk** [comment]
I don't think this is a Docker problem, maybe a Mattermost issue.

**Comment by EagleEnergy** [comment]
> I don't think this is a Docker problem, maybe a Mattermost issue.

I think it's a Postgres version. I'll try tu upgrade the db container to Postgres 9.6 or more

**Comment by EagleEnergy** [comment]
Hello, 

Today I have upgrade the postgresql version and it's solve the problem.
Now my two core are used for a searching query.

This is the statistics:

PSQL 9.4 => Searching the word "Unicorn", queryduring arround 13600 ms

PSQL 9.6 => Searching the word "Unicorn", query during arroung 4300 ms
