### ISSUE TITLE
Official docker image version 6+

### ISSUE THREAD

**Issue by cpoetter** [mattermost/mattermost-docker#385]
Hi,

I am thinking of deploying Mattermost on our production server. We have already a Postgres database and an nginx load balancer with SSL termination running from other projects. Therefore the *only* thing missing is Mattermost itself, if I understand that correct from the *docker-compose* file.

When I browse docker hub, the most logical choice for me seems to be **mattermost/mattermost-prod-app**, but the description contains `This repo will be deprecated in the Mattermost version 6`. Therefore my question:

Will there be a different image for version 6+? Will **mattermost/mattermost-enterprise-edition** and **mattermost/mattermost-team-edition** replace the previous image? Or is there not going to be any official image on docker hub anymore following version 5 and the only way to deploy Mattermost is with this repository?

I could not find any information regarding the question above. If I start deploying Mattermost now, I want it to be future proof :-)

Thank you very much for your help!

**Comment by cpoetter** [comment]
I just read https://github.com/mattermost/mattermost-docker/issues/361. Is this the reason for the description I quoted above? So there will still be a Mattermost image on docker hub, just under a different URL? Something like https://hub.docker.com/_/mattermost/?

The correct image for now would then be **mattermost/mattermost-prod-app**, which would afterwards be **mattermost-prod-app**?

**Comment by pichouk** [comment]
The reason `mattermost/mattermost-prod-app` is marked as *deprecated* is because we wanted to push the Team **and** the Enterprise Edition to Docker Hub. So `mattermost/mattermost-enterprise-edition` and `mattermost/mattermost-team-edition` arrived and you should use them now. They are official Mattermost images build by Mattermost Inc.

There is a plan (cc @cpanato) to rename those images to `mattermost-ee` and `mattermost-te`, don't know when it will be ready.

Also there is a plan to try to have a *Docker Hub official* image (on #361), but it's just the beginning of discussions about it.

**Comment by cpoetter** [comment]
Thanks @pichouk!

Is the Dockerfile itself basically the same for the new images as it was for the old one? What I mean is are the volumes, etc. identical?

Also could you add a `latest` tag to the new images like you did with the old one? That would make it much easier to update :)

**Comment by pichouk** [comment]
It's the same Dockerfile from this repository. The only difference is naming and Mattermost editions :)
I can't about the latest tag, maybe @cpanato can.

**Comment by cpoetter** [comment]
FYI: I just downloaded the `mattermost/mattermost-team-edition:5.10.0` image and it still tells me in the *About Mattermost* windows that it is the **Enterprise Edition**.

**Comment by cpanato** [comment]
@cpoetter i will check and fix

**Comment by cpanato** [comment]
fixed @cpoetter thanks so much for the catch!

**Comment by cpoetter** [comment]
@cpanato Thanks for the fast fix!

While you are at it, could you add the `latest` tag, like it was done with the "old" `mattermost/mattermost-prod-app` image? That would make an update a lot easier!

Thank you very much.

**Comment by cpanato** [comment]
sure thing

**Comment by cpanato** [comment]
@cpoetter done as well for team edition

**Comment by cpoetter** [comment]
@cpanato Thank you very much! 

The *downgrade* from enterprise to team edition also worked flawless :)

**Comment by jasonblais** [comment]
> The reason mattermost/mattermost-prod-app is marked as deprecated is because we wanted to push the Team and the Enterprise Edition to Docker Hub. So mattermost/mattermost-enterprise-edition and mattermost/mattermost-team-edition arrived and you should use them now. They are official Mattermost images build by Mattermost Inc.

@pichouk What would be your thoughts on adding a note of this at https://hub.docker.com/u/mattermost. Perhaps modifying the note to say

```
This repo will be deprecated in Mattermost 6.0, in favor of `mattermost/mattermost-enterprise-edition` and `mattermost/mattermost-team-edition`.
```

For the `mattermost-enterprise-edition` and `mattermost-team-edition` images, we could also say `The official Docker image for Mattermost {Team/Enterprise} Edition.`

The above changes would help make it more obvious for new admins to decide which Docker image they should use.

![image](https://user-images.githubusercontent.com/13119842/56702125-64177380-66d0-11e9-9daf-f9697ea9f125.png)

**Comment by HarriLuxus** [comment]
So after the 6+ update we can use this repos docker-compose.yml but the difference is that we use images without building? Have somebody tested it works?

**Comment by pichouk** [comment]
@jasonblais Totally agree ! Good idea, can you do this ? :)

@HarriLuxus After 6+ upgrade, the `docker-compose.yml` file will only be an example (see #366). But you will be able to use images from Docker Hub or build it yourself from this repository. Nothing will change on this side.

**Comment by jasonblais** [comment]
@pichouk Certainly. I've created a ticket as I don't think I have permissions to update the descriptions: https://mattermost.atlassian.net/browse/MM-15327
