### ISSUE TITLE
Android app can't find server

### ISSUE THREAD

**Issue by tomtruitt** [mattermost/mattermost-docker#40]
![screenshot_20160719-215148](https://cloud.githubusercontent.com/assets/10718256/16972624/0da9dd4e-4dfb-11e6-9d36-c77a8b6293ba.png)

**Comment by tomtruitt** [comment]
Works on iPhone however

**Comment by tomtruitt** [comment]
![image](https://cloud.githubusercontent.com/assets/10718256/16972896/0c90bf16-4dfd-11e6-98be-dee9ee96b7ca.png)

**Comment by DavidLu1997** [comment]
Hello @tomtruitt,

It seems like you do not have the most up-to-date version of the Android application, please update it by going to the Google Play Store.

If this issue still reproduces for you after updating, can you comment below with your configuration details, including Mattermost server version, Android OS version, and model of the phone? Thank you :)

**Comment by tomtruitt** [comment]
thanks for responding so quickly. this app was downloaded from the play store just before i opened the issue.. mattermost server install is docker so i'm guessing 3.2.0 phone is samsung galaxy s7 edge.... i was using it earlier today on a different install.. and another user is currently logged in fine from their ipone

**Comment by tomtruitt** [comment]
i just requested beta access

**Comment by DavidLu1997** [comment]
Can you double check your server version by going to the left-side dropdown > About Mattermost? I could not connect to your server with neither the beta Android app nor the store Android app (both should be the same right now). You may have to upgrade your Mattermost installation if your server is running a version before v3.0

**Comment by tomtruitt** [comment]
![image](https://cloud.githubusercontent.com/assets/10718256/16973299/8c1a4d8a-4e00-11e6-9602-9956e822d2db.png)

**Comment by tomtruitt** [comment]
@DavidLu1997 do you know how I should proceed?

**Comment by it33** [comment]
Hi @tomtruitt, 

If you're using self-signed certificates the client might not be able to reach the HTTPS link. 

If this doesn't solve your issues, please post to the [troubleshooting forum](https://forum.mattermost.org/c/general/trouble-shoot)? 

It's not clear this issue is Docker-related so it's a little weird having it in this issue list.

**Comment by tomtruitt** [comment]
I installed using docker and immediately had this issue so posted here not having had involvement in any other repo. I did try mattermost -android first but didn't get anywhere. 

It's works fine in iOS. Is this an Android problem? I can't use the Android app if using a self signed certificate?

**Comment by tomtruitt** [comment]
Obviously I didn't know what the source of the problem was when I posted

**Comment by DavidLu1997** [comment]
@tomtruitt I think @it33 is right on this one, you may have to resort to using the Android browsers, or not use a self-signed certificate.

**Comment by tomtruitt** [comment]
That is unfortunate... This is do to an Android security policy?

**Comment by tomtruitt** [comment]
Due

**Comment by tomtruitt** [comment]
my cert is from let's encrypt... that's not considered self signed is it? @it33 @DavidLu1997

**Comment by tomtruitt** [comment]
my apologies.. i had ssl_certificate pointed to cert.pem like in the default mattermost-ssl instead of fullchain.pem as in the documentation.

**Comment by it33** [comment]
Thanks @tomtruitt for the update, could we ask your help to update your forum post so people facing similar issues know the fix? It's an easy step to miss and your update could help others find the issue sooner.

**Comment by tomtruitt** [comment]
Yes certainly will

**Comment by tomtruitt** [comment]
I need one of my deleted posts to fully delete in order to post

**Comment by tomtruitt** [comment]
So I fixed my problem. don't know if this is what others are experiencing but in mattermost-ssl  ssl_certificate points to cert.pem but should be changed to fullchain as in the documentation. there may be a difference in ciphers too. Here is what worked for me:
```
server {
   listen         80;
   server_name    mattermost.example.com;
   return         301 https://$server_name$request_uri;
}

server {
   listen 443 ssl;
   server_name mattermost.example.com;

   ssl on;
   ssl_certificate /etc/letsencrypt/live/yourdomainname/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/yourdomainname/privkey.pem;
   ssl_session_timeout 5m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;

   location / {
      gzip off;
      proxy_set_header X-Forwarded-Ssl on;
      client_max_body_size 50M;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Frame-Options SAMEORIGIN;
      proxy_pass http://app:APP_PORT;
   }
}
```
Could be other differences too like the SSL listen port. But using this with my domain name instead of just changing my domain name in the existing file works.
