### ISSUE TITLE
Using Mattermost Platform CLI on docker install

### ISSUE THREAD

**Issue by JohnBueno** [mattermost/mattermost-docker#42]
Please excuse my ignorance because I am quite new to docker but I would like to use the Mattermost command line tools (https://docs.mattermost.com/administration/command-line-tools.html) on an instance of mattermost I have installed with docker-compose.  When I try to run ```platform``` I am getting command not found.  The docs say this must be run from the directory where the Mattermost platform is installed but I am not sure where this would be if installed via Docker.  Any help would be appreciated.

**Comment by npcode** [comment]
The directory is `/mattermost` in your mattermost container. Try this:
```
docker exec -it <your-mattermost-container-name> /bin/bash
cd /mattermost
bin/platform -help
```

The container name may be `mattermostdocker_app_1` if you installed mattermost with `docker-compose.yml` in this repository.

Good luck to you!

**Comment by JohnBueno** [comment]
That works thank you so much!!!
