### ISSUE TITLE
incorrect directory for certificate files?

### ISSUE THREAD

**Issue by error9900** [mattermost/mattermost-docker#45]
README.md says:

> Put your SSL certificate as ./volumes/cert/cert.pem and the private key that has no password as ./volumes/cert/key-no-password.pem.

docker-compose.yml says:

> &#35; This directory must have cert files
>   - ./volumes/web/cert

**Comment by npcode** [comment]
Thanks for the report. Fixed by https://github.com/mattermost/mattermost-docker/commit/914b85dec45a077a9d11270ca88d1e58e0e9a9f9
