### ISSUE TITLE
what's going on with env variables?

### ISSUE THREAD

**Issue by felixsanz** [mattermost/mattermost-docker#481]
Hi, from the readme:

MM_USERNAME: database username
MM_PASSWORD: database password
MM_DBNAME: database name
DB_HOST: database host address
DB_PORT_NUMBER: database port
MM_SQLSETTINGS_DRIVERNAME : mysql

why some variables are `MM_`, another `DB_`, and another `MM_SQLSETTINGS_`? This is crazy!

**Comment by Salatfreak** [comment]
This repository has quite some outdated code in it. MM_* variables are usually used by mattermost directly to [replace settings from the config.json](https://docs.mattermost.com/administration/config-settings.html). The others are used by the [entrypoint.sh](https://github.com/mattermost/mattermost-docker/blob/master/app/entrypoint.sh). You only need either the MM_SQLSETTINGS_DRIVERNAME or the MM_USERNAME and MM_PASSWORD (and optionally MM_DBNAME, DB_HOST and DB_PORT_NUMBER). The [official docker images](https://hub.docker.com/u/mattermost) don't have these extra variables though. You can deploy the team-edition e. g. with the following docker-compose.yml:
```yaml
```
