### ISSUE TITLE
Kubernetes manifests?

### ISSUE THREAD

**Issue by rothgar** [mattermost/mattermost-docker#49]
I have converted this to working on Kubernetes and I wasn't sure if you would like to have them in this repo (perhaps in a kubernetes sub folder). If not I can maintain them in my own repo but I thought I should ask before doing work to make them generic configs and submitting a PR.

**Comment by npcode** [comment]
It would be great if you send the pull request! I couldn't make the manifests because I'm not using kubernetes...

**Comment by rothgar** [comment]
Sorry for the delay. I'll try to put them together this weekend and send the PR.
