### ISSUE TITLE
Make MM_VERSION configurable

### ISSUE THREAD

**Issue by pat-s** [mattermost/mattermost-docker#499]
In `app/Dockerfile` `MM_VERSION` is set as an `ENV`.

If it would be an `ARG`, users could overwrite it in the `docker-compose` build args and specify a custom version.

If none is given, the upstream default is used.
This would be  a one-line change. Happy to do a PR if you agree.

**Comment by pat-s** [comment]
ping @cpanato

**Comment by cpanato** [comment]
@pat-s Hello! are you willing to propose this change?

**Comment by pat-s** [comment]
@cpanato Anything preventing the PR from being merged?
