### ISSUE TITLE
Updating to the Latest Version

### ISSUE THREAD

**Issue by nickian** [mattermost/mattermost-docker#505]
I was able to update my instance, but not with the directions provided. I had a quick question:

When I run `git pull`, I get this message:

```
error: Your local changes to the following files would be overwritten by merge:
	.travis.yml
	README.md
	app/Dockerfile
	db/Dockerfile
	web/mattermost-ssl
Please commit your changes or stash them before you merge.
Aborting
```

So, what I ended up doing was just cloning the repository to a new directory, matching the docker-compose.yml values that I needed, deleting the `volumes` folder from the new pull, then doing `cp -r volumes` from my old folder to my new one.

Is there an easier way to do this? Maybe this is a git question, not a Mattermost question, but I'm sure someone else will come across this. Thanks!

**Comment by jgerstbe** [comment]
If you did not modify these files yourself you can use `git checkout <filename>` to get the original file from your last state of the repo. After that `git pull` should work just fine.

**Comment by nickian** [comment]
Ok, thanks! I will try that next time.
