### ISSUE TITLE
Getting Websock error 

### ISSUE THREAD

**Issue by mastreips** [mattermost/mattermost-docker#52]
I am logging the following error with my ElasticBean Mattermost instance on AWS:

websocket connect err: websocket: could not find connection header with token 'upgrade

as far as I can tell there is no nginx configuration and I think I have traced the problem to the instance being automatically setup for load balancing (which AWS service may not support websockets). Is there a tweak to the Dockerrun.aws.json that could override this issue?

**Comment by npcode** [comment]
Well, I think you don't need a load balancer because [mattermost app doesn't support scaling](https://github.com/mattermost/platform/issues/2466#issuecomment-198144418). Is it possible to disable the load balancer?

**Comment by mastreips** [comment]
It came with the elasticbean installation - I just followed the setup here: https://docs.mattermost.com/install/docker-ebs.html.  Disabling the load balancer has taken Mattermost offline

**Comment by xcompass** [comment]
@mastreips have you solved this issue?

**Comment by pichouk** [comment]
I close this issue since it seems to have not been updated in months.
@mastreips If you still have any troubles, feel free to reopen :slightly_smiling_face:
