### ISSUE TITLE
release-5.33 Uses Wrong Version of Postgres

### ISSUE THREAD

**Issue by davidbartonau** [mattermost/mattermost-docker#528]
I just tried upgrading from 5.31 and mattermost keeps restarting with the error:

Error: cannot create store: minimum required postgres version is 10.0; found 9.426

The db Dockerfile contains: `FROM postgres:9.4-alpine`

As I understand it, this means a manual backup and restore of the database, since the postgres container doesn't automatically upgrade data.  I'm going to give it a go and report back here.

**Comment by davidbartonau** [comment]
Unfortunately, postgres:10-alpine does not have python-dev and since I don't know python or alpine Linux, I am a bit stuck at this point.

**Comment by EugenMayer** [comment]
https://github.com/mattermost/mattermost-docker/pull/529

**Comment by bor8** [comment]
![grafik](https://user-images.githubusercontent.com/5301068/115140872-c5f9e200-a039-11eb-8140-b4b166a082de.png)

Make good backup and do:

https://github.com/mattermost/mattermost-docker/issues/489#issuecomment-790277661

Read the whole ticket when you have problems.
