### ISSUE TITLE
Mattermost mobile app server warning message after upgrade

### ISSUE THREAD

**Issue by band** [mattermost/mattermost-docker#534]
Thanks for the useful and easy to manage docker version of mattermost. I upgraded my running Mattermost docker as described; just a few updates to the compose yaml file needed.

I assumed this upgrade would stop this warning that keeps showing up on the mobile app (v1.42.1):

"Server upgrade required. This server version is unsupported ....  Upgrading to server version 5.31.3 or later is required."

But the message still comes up. Is there a way to determine what version the server is running? I am missing something here and any help is appreciated.

**Comment by oguera** [comment]
Hey! 
The current Dockerized Version of Mattermost is not able to upgrade to PSQL10 right now.

See the Warning in the Readme:
```
WARNING:
The current state of this repository doesn't work out-of-the box since Mattermost server v5.31+ requires PostgreSQL versions of 10 or higher.

We're actively working on a fix to this repository. Until then, please refer to these upgrade instructions: https://github.com/mattermost/mattermost-docker/issues/489#issuecomment-790277661
```

You can either wait for the migration or use the upgrade instructions at your own risk.

Hope that helps! :)

**Comment by band** [comment]
Thanks for the note. It turns out that I missed setting the MM_VERSION variable in the docker-compose.yml file; so the latest software was not installed.
