### ISSUE TITLE
Why Mattermost releases 5.34, 5.34.1, 5.34.2, 5.35, 5.35.2 missing in mattermost-docker releases?

### ISSUE THREAD

**Issue by stephane-klein** [mattermost/mattermost-docker#537]
HI,

why this  Mattermost releases

- [5.34](https://mattermost.com/blog/mattermost-release-v5-34/)
- [5.34.1](https://mattermost.com/blog/mattermost-5-34-1-released/)
- [5.34.2](https://mattermost.com/blog/mattermost-5-34-2-released/)
- [5.35](https://mattermost.com/blog/mattermost-release-v5-35/)
- [5.35.2](https://mattermost.com/blog/mattermost-5-35-2-5-34-3-and-5-33-4-released/)

missing in https://github.com/mattermost/mattermost-docker/releases ?

Best regards,
Stéphane

**Comment by vasilyevmn** [comment]
https://github.com/mattermost/mattermost-docker/issues/535

**Comment by stephane-klein** [comment]
Thanks for #535 information, I close this issue 👍
