### ISSUE TITLE
Building DB Failes

### ISSUE THREAD

**Issue by Pezhvak** [mattermost/mattermost-docker#542]
Running `docker-composer build` results in this error:

```
1 error; 399 MiB in 100 packages
The command '/bin/sh -c apk add --no-cache       build-base       curl       libc6-compat       libffi-dev       linux-headers       python3-dev       py3-pip       py-cryptography       pv       libressl-dev     && pip install --upgrade pip     && pip --no-cache-dir install -c pip-constraints.txt 'wal-e<1.0.0' envdir     && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*' returned a non-zero code: 1
ERROR: Service 'db' failed to build : Build failed
```

Note that this is not happening before https://github.com/mattermost/mattermost-docker/commit/c79ed62e13c8a3ceaf897c88b9e63478d32d8aa1

**Comment by zzir** [comment]
`db/Dockerfile` line 18 is missing a backslash.


```
Building db
Sending build context to Docker daemon  6.144kB
Error response from daemon: dockerfile parse error line 19: unknown instruction: &&
ERROR: Service 'db' failed to build : Build failed
```

**Comment by Pezhvak** [comment]
@zzir  are you talking about the current state of the repo?

**Comment by zzir** [comment]
> @zzir are you talking about the current state of the repo?

about https://github.com/mattermost/mattermost-docker/pull/543

**Comment by Pezhvak** [comment]
@zzir Fixed, thanks for mentioning. https://github.com/mattermost/mattermost-docker/pull/543/commits/796937944ba1b226ff31a570a4c102f5296fb23e
