### ISSUE TITLE
Pull DB settings from environment variables. 

### ISSUE THREAD

**Issue by 5ak3t** [mattermost/mattermost-docker#55]
The db settings need to be manually updated at config, make_db, and app/dockerfile. Can these be updated to read from one file / environment variables?

**Comment by npcode** [comment]
You can set username, password and dbname by using `MM_USERNAME`, `MM_PASSWORD` and `MM_DBNAME` environment variables in `db` section in `docker-compose.yml`.

**Comment by xcompass** [comment]
Since PR #56 is merged, I'm closing this issue now.
