### ISSUE TITLE
Install on osx

### ISSUE THREAD

**Issue by npcode** [mattermost/mattermost-docker#6]

**Comment by poksion** [comment]
...
db_1 | Data page checksums are disabled.
db_1 |
db_1 | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1 | initdb: could not create directory "/var/lib/postgresql/data/pg_xlog": Permission denied
db_1 | initdb: removing contents of data directory "/var/lib/postgresql/data"
db_1 | The files belonging to this database system will be owned by user "postgres".
db_1 | This user must also own the server process.
db_1 |
db_1 | The database cluster will be initialized with locale "en_US.utf8".
db_1 | The default database encoding has accordingly been set to "UTF8".
db_1 | The default text search configuration will be set to "english".
db_1 |
db_1 | Data page checksums are disabled.
db_1 |
db_1 | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1 | initdb: could not create directory "/var/lib/postgresql/data/pg_xlog": Permission denied
db_1 | initdb: removing contents of data directory "/var/lib/postgresql/data"

**Comment by npcode** [comment]
@poksion It seems related with https://github.com/docker/toolbox/issues/292

**Comment by xcompass** [comment]
I'm running this with [docker for mac](https://beta.docker.com/) (in beta right now) without any issue.

**Comment by npcode** [comment]
@xcompass That's good news! It sounds like docker for mac works differently from the old vm way. Thank you for letting me know.
