### ISSUE TITLE
PLATFORM_PORT_80_TCP_PORT can be overridden, but hostname of app cannot. 

### ISSUE THREAD

**Issue by JohnOmernik** [mattermost/mattermost-docker#60]
In the web setup, PLATFORM_PORT_80_TCP_PORT can be passed as an environment variable if we need to run the MM App on a different port. The docker_entry seds the APP Port in the nginx config.  

However, the app is hard coded and forces this to be Docker Compose only.  

Ideal: Default to docker compose ( a value of "app") but allow an ENV variable to be passed with the application hostname if we are using a different clustering technology with our own service discovery.  

Note: the Database/App containers already do this with
(in App docker entry:)
DB_HOST=${DB_HOST:-db}
DB_PORT_5432_TCP_PORT=${DB_PORT_5432_TCP_PORT:-5432}

We could do the same thing:
APP_HOST=${APP_HOST:-app}
PLATFORM_PORT_80_TCP_PORT=${PLATFORM_PORT_80_TCP_PORT:-80}

and then when doing the sed in the docker_entry, fix both items.

**Comment by xcompass** [comment]
@JohnOmernik Thanks for the suggestion. I guess in most of the case, you don't need to change "app". Could you tell me a little bit more about your use case? Would you like to send a PR for this feature?

**Comment by xcompass** [comment]
Closing this for now. Feel free to reopen it if there is more question.
