### ISSUE TITLE
Problems with SMTP

### ISSUE THREAD

**Issue by maackle** [mattermost/mattermost-docker#61]
Is this container supposed to be able to talk over SMTP ports (25 or 465)? I tried getting this to talk to postfix on the same machine, and also tried sending mail through amazon SES -- neither worked, the SMTP connection failed.

**Comment by npcode** [comment]
> Is this container supposed to be able to talk over SMTP ports (25 or 465)?

Yes, the containers doesn't block any outgoing port. I suspect you have some network problems between docker container and host machine.

**Comment by xcompass** [comment]
What SMTP server IP/address were you using when you tried on the same machine. If your postfix is running on your host and you are running the container, you need to point the SMTP server to your host docker IP.

**Comment by xcompass** [comment]
Closing this for now. Feel free to reopen if there is any question.

**Comment by karsalfrink** [comment]
@maackle I am running into the same issue—did you find a fix and if so, what is it?

**Comment by karsalfrink** [comment]
After some more poking around I got this to work. 

For those who stumble across this issue looking for a fix, here is what I did. 

_I am assuming you have gone through the basic [Mattermost Docker installation](https://github.com/mattermost/mattermost-docker), and have set up Postfix as a regular service on your host machine (I followed [this guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-14-04))._

1. On the host machine do `ifconfig` and find the ip address of the [`docker0` bridge network](https://docs.docker.com/engine/userguide/networking/#default-networks)
2. In Mattermost's system console set up email notifications as per [these instructions](https://docs.mattermost.com/install/smtp-email-setup.html) under 'postfix' but enter the ip address from step 1 in stead of localhost.
3. Find the ip address of the `mattermostdocker_web_1` container using this command: `docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)` ([source](https://stackoverflow.com/a/34749387))
4. Add the ip address from step 3 into `/etc/postfix/main` to `mynetworks`, save the file and make sure you do `service postfix restart`
5. Back in Mattermost, hit the 'Test Connection' button. The admin user should receive a test email from the configured from address.

I am no expert so I do not know if this is the 'correct' way to do this, but it works.
