### ISSUE TITLE
Where is https://hub.docker.com/r/mattermost/webrtc/ Dockerfile?

### ISSUE THREAD

**Issue by harobed** [mattermost/mattermost-docker#63]
Where is https://hub.docker.com/r/mattermost/webrtc/ Dockerfile?

**Comment by enahum** [comment]
Hi @harobed you should be able to find the Dockerfile in the [mattermost-webrtc repo](https://github.com/mattermost/mattermost-webrtc)

**Comment by jasonblais** [comment]
@xcompass, this is fine to close,
