### ISSUE TITLE
Mattermost 3.5

### ISSUE THREAD

**Issue by fculpo** [mattermost/mattermost-docker#64]
Hi,
Could you update your Docker images to use the new 3.5 release ?

Thx

**Comment by jasonblais** [comment]
Created a pull request for it, see https://github.com/mattermost/mattermost-docker/pull/65- @npcode, can you help with review?

**Comment by fculpo** [comment]
Thank you.
I guess the same applies for the 2 others containers (db and web) ?

**Comment by fculpo** [comment]
Please tag the 3.5.1 release for Docker hub to reflect it

**Comment by esethna** [comment]
@fculpo the [docker hub image](https://hub.docker.com/r/mattermost/platform/) is updated to 3.5.1. The source repo is [mattermost/mattermost-docker-preview](https://github.com/mattermost/mattermost-docker-preview).

**Comment by fculpo** [comment]
I am using https://hub.docker.com/r/mattermost/mattermost-prod-app/ and https://hub.docker.com/r/mattermost/mattermost-prod-db/ and they don't have 3.5.1 atgs.

**Comment by esethna** [comment]
Ah, got it, thanks for pointing this out @fculpo. We are in the process of transitioning maintainership of the repos and then we will make sure the tags are updated for all the docker containers.

**Comment by jasonblais** [comment]
@compass 

The tags on the docker hub repos are automatically generated, but some of them are still pointing to 3.4.1. Wondering if you'd be able to help take a look?

 - https://hub.docker.com/r/mattermost/mattermost-prod-web/tags/
 - https://hub.docker.com/r/mattermost/mattermost-prod-db/tags/
 - https://hub.docker.com/r/mattermost/mattermost-prod-app/tags/

**Comment by xcompass** [comment]
@fculpo 3.5.1 is tagged. Do you need 3.5.0? I need to figure out which commit is for 3.5.0 otherwise here is the new tag: https://hub.docker.com/r/mattermost/mattermost-prod-app/tags/

**Comment by fculpo** [comment]
3.5.1 is fine for me. Thank you
