### ISSUE TITLE
Dockfile not updated on team-and-enterprise branch 

### ISSUE THREAD

**Issue by serco-chen** [mattermost/mattermost-docker#70]
[Line of Code](https://github.com/mattermost/mattermost-docker/blob/team-and-enterprise/app/Dockerfile#L6)

Installation documentation still suggests using `team-and-enterprise` branch for production, so it would be nice if Dockfile on that branch get updated to v3.5.1.

**Comment by jasonblais** [comment]
Submitted a PR here, thanks for the note: https://github.com/mattermost/mattermost-docker/pull/71

**Comment by xcompass** [comment]
PR #71 is merged.
