### ISSUE TITLE
No sign up button

### ISSUE THREAD

**Issue by xtrinch** [mattermost/mattermost-docker#75]
Not sure if this is the appropriate place to post this, but I see no sign up buton, and I have enabled user account creation with:

```
  "EmailSettings": {
        "EnableSignUpWithEmail": true,
       ....
```

I know the settings are working because it's picking up my login with gitlab settings (I can see the login with gitlab button) and mailserver settings.

Any ideas?

**Comment by jasonblais** [comment]
What value is your `EnableOpenServer` setting set to?

https://docs.mattermost.com/administration/config-settings.html#enable-open-server

**Comment by xtrinch** [comment]
It's set to true. The first user was able to sign up, but all others have to sign up via an invite link.

**Comment by jasonblais** [comment]
Hmm, okay. Just to confirm, the "Sign Up" button you're referring to is the "Create one now" link on the sign in page? 

![image](https://cloud.githubusercontent.com/assets/13119842/21720166/b508e54c-d3ef-11e6-83bc-9a5f04411736.png)

If so, would you be interested signing up to our [public Mattermost community instance](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676)? I'd like to know more details on your config.json file to replicate your setup and try reproduce the issue, but some of it might be confidential.

If you sign up, let me know your username and I'll direct message you (or you can start a conversation with me -  my username is `@jason`)

**Comment by xtrinch** [comment]
Yes, that one

**Comment by xcompass** [comment]
@xtrinch just want to confirm one thing, when you check the EnableOpenServer, did you do it through the config.json or system console? If you did with json file, could you double check the system console/security/sign up? 

I just tried. Default is false and I need to go to the console switch to true before I can see the sign up link.

**Comment by xtrinch** [comment]
Well thank you, that worked. I only had it in config.json and that didn't work
