### ISSUE TITLE
CLI usage

### ISSUE THREAD

**Issue by banzo** [mattermost/mattermost-docker#76]
I was trying to use the CLI and ran into this issue:

```
$ docker exec <my_container_id> mattermost/bin/platform -team_name="<my_team_name>" -list_channels
[14:08:53 CET 2017/01/06] [EROR] (main.main:107) Unable to load mattermost configuration file:  no language found in "config.template.json"
```

I stumbled upon [this old thread](http://forum.mattermost.org/t/solved-panic-failed-to-load-system-translations/959/7) that inspired me to try this which seems to work:

```
$ docker exec <my_container_id> bash -c 'cd mattermost/i18n && mattermost/bin/platform -team_name="<my_team_name>" -list_channels'
```

Unless there is a less convoluted way to achieve this, it might be worth mentioning that workaround in the README.

**Comment by xcompass** [comment]
Which version are you using? It seems it's fixed in 2.1.

**Comment by banzo** [comment]
I was using the latest Mattermost version (3.5.1).

Today I tried again and the error message is different:

* this repo's master branch (Mattermost 3.6)
* Docker 1.13.0-rc6
* Docker Compose 1.10.0-rc2
* OS X 10.12.2

```
$ git clone https://github.com/mattermost/mattermost-docker.git
$ cd mattermost-docker
$ docker-compose up -d
$ docker exec <app_container_id> mattermost/bin/platform team create --name <my_new_team_name> --display_name "<my_new_team_description>"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4105cd]

goroutine 1 [running]:
panic(0xbdc8c0, 0xc420014040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.getMockContext(0xc4200b4278)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/oldcommands.go:1098 +0x10d
main.createTeamCmdF(0x1068080, 0xc42000ecc0, 0x0, 0x4, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/team.go:95 +0x37e
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x1068080, 0xc42000ec40, 0x4, 0x4, 0x1068080, 0xc42000ec40)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420132000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420132000, 0xc420116470, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f
```

**Comment by xcompass** [comment]
It seems the platform binary is a little bit picky on the current directory. The current working directory has to be "/mattermost/bin".  The workaround is to run the command as follow:
```
docker exec -it <Container_ID> bash -c "cd mattermost/bin && ./platform ......."
```

@jasonblais do you think someone from mattermost team could look at this issue? I think it's in the go binary and it may affect non-docker versions as well.

**Comment by banzo** [comment]
Thanks for your response. That is how I understand it too.

If I am not mistaken Mattermost runs as `root` inside the container, whereas it runs as `mattermost` user in a regular install. That `mattermost` user probably has an alias to the `platform` binary in his `.bashrc` or something.

**Comment by jasonblais** [comment]
Hey @xcompass, I think the platform binary is expected to be in the `mattermost/bin` directory:
https://forum.mattermost.org/t/problem-following-instructions-installing-mattermost-2-2-0-in-ubuntu-14-04-connecting-3-ubuntu-machines/1386/6?u=jasonblais

**Comment by xcompass** [comment]
@jasonblais Yes, it is in the `mattermost/bin` in the docker image. However, it also expect the current working directory is `mattermost/bin`, which prevents you to run it from other location. That's why you need to `cd mattermost/bin` and then run `./mattermost ...`. It maybe loading some files using current working directory as a reference. However, if you look at other unix commands, it doesn't matter where you run the command from. The config files are loaded either from an absolute directory (e.g. /etc/xx_config) or a directory relative to the binary (e.g. same directory as the binary). 

@banzo I don't think adding a alias in .bashrc would work.

**Comment by pichouk** [comment]
This issue seems to be more about a Mattermost binary behavior than a Docker behavior. Should we move this to [mattermost/platform](https://github.com/mattermost/platform) repository ?

Also, I think that https://github.com/mattermost/mattermost-docker/commit/2a0cf0cb21b3e9d769c2646047cf1186712eaac1 fixed the issue (by setting a workdir and adding Mattermost binary to PATH).

**Comment by jasonblais** [comment]
@pichouk We have since made some improvements to our CLI documentation, clarifying which directory you must be in to execute the CLI commands

https://docs.mattermost.com/administration/command-line-tools.html#using-the-cli

Wondering if that would resolve the issue discussed here?

**Comment by pichouk** [comment]
In fact I just test this with my server, and it works.
```
user@myserver:~$ docker exec -it mattermost-app platform help
Mattermost offers workplace messaging across web, PC and phones with archiving, search and integration with your existing systems. Documentation available at https://docs.mattermost.com

Usage:
  platform [flags]
  platform [command]

[...]
```
Since the working directory of the application container is `/mattermost/bin` it is easy to use the `platform` binary.

So I think we can close :)
