### ISSUE TITLE
Huge amount of socket.io log spam

### ISSUE THREAD

**Issue by Kiina** [mattermost/mattermost-docker#78]
So after like a week of usage I noticed a huge 20gb file in /var/lib/docker/containers/f80b04e72da1d722b9aa5fe3e27b670bb56536c825c14279e872cd9475f4c326/ called f80b04e72da1d722b9aa5fe3e27b670bb56536c825c14279e872cd9475f4c326-json.log. This is the log Output for my mattermost_web container. If you look into the file or the logs you see this:

`{"log":"172.17.0.8 - - [09/Jan/2017:15:15:40 +0100] \"GET /socket.io/?token=*censored* HTTP/1.1\" 200 2246 \"-\" \"node-XMLHttpRequest\"\n","stream":"stdout","time":"2017-01-09T14:15:40.331612674Z"}`

about 20 times every 5 seconds

**Comment by xcompass** [comment]
@Kiina Could you tell me a little bit more about your setup? Did you enabled any settings? I couldn't replicate it with default setup. E.g. docker-compose up

**Comment by Kiina** [comment]
For some reason it stopped after a few days. Not sure what happened, wasn't able to replicate since then. But maybe someone observed the same problem
