### ISSUE TITLE
Instructions for Let's encrypt are too vague

### ISSUE THREAD

**Issue by kocio-pl** [mattermost/mattermost-docker#82]
It's not clear from [documentation](https://github.com/mattermost/mattermost-docker#install-with-ssl-certificate) what you need to do with [Let's encrypt](https://letsencrypt.org/) certificates. I was not sure if I need to take care of them myself or the Docker image will do the trick once this option is turned on and if not, which exact files are needed and how to make them accesible to a Mattermost container.

It would be also useful to tell about certification renewal if it can make some problems (for example with Docker on port 80?), because it's one of the crucial features of Let's encrypt system. I don't like to turn Mattermost down every 2 months just to have fresh certificates and HTTPS working.

I've only found this and hope it will work for me too:
http://forum.mattermost.org/t/solved-how-to-use-lets-encrypt-with-the-docker-image-of-mattermost/2013

**Comment by xcompass** [comment]
@kocio-pl I don't think the image handles SSL automatically. You have to generate them yourself. It doesn't mention the Let's encrypt anywhere. And it clearly states that you need to put your SSL certificate and private key as specific names on the step 2. 

For now, if you would like to use LE for the SSL, you will need to generate the cert outside the mattermost container. Maybe use a separate container. To update the certs, you don't have to shutdown mattermost container, just web container. If you want HA, you can have multiple web containers behind a load balancer. When you update the cert, you just rotate the web containers.

If you have any suggestion to make the docs better, please feel free to send a PR. You can also send a PR to add LE support.

**Comment by xcompass** [comment]
Closing this for now. Feel free to reopen it for more discussion.
