### ISSUE TITLE
Dead link on README

### ISSUE THREAD

**Issue by Niceplace** [mattermost/mattermost-docker#84]
At the end of the README, the following line contains a link "For the server configurations, see prod-ubuntu.rst of mattermost.".

The link is "prod-ubuntu.rst" which points to https://github.com/mattermost/docs/blob/master/source/install/prod-ubuntu.rst. 

This link seems to be broken.

**Comment by jasonblais** [comment]
Thanks @Niceplace for the note, I've submitted a pull request for it.

The Ubuntu guides can be found here, looks like the link got broken due to the recent installation guide updates: https://docs.mattermost.com/install/install-ubuntu-1404.html
