### ISSUE TITLE
IOS 3.5 version not able to connect to 3.6.0 version server

### ISSUE THREAD

**Issue by cinqs** [mattermost/mattermost-docker#93]
I set up a server on docker 1.12 , but I am not able to use IOS app to connect the server.
It reads:

    We could not connect to the Mattermost server or the server running in an incompatible version.

**Comment by xcompass** [comment]
Could you try server 3.6.2 version?

**Comment by pichouk** [comment]
@cinqs Is this issue fixed ?

**Comment by pichouk** [comment]
Closing since there were no answers in few months.
