### ISSUE TITLE
Steps for Upgrading from 3.4.0 to 3.6.2

### ISSUE THREAD

**Issue by ismarslomic** [mattermost/mattermost-docker#96]
Hi,
September 2016 I cloned team-and-enterprise branch (22df21a) on a Virtual Machine and _70_ users has used Mattermost since then. We have _19 061_ posts and _26_ channels.

We would like to do git pull and rebuild Docker images to latest version of this branch, in order to upgrade to latest Mattermost version v3.6.2.

What are the upgrading steps, in order to not loose any existing data? Is it as easy as just to do git pull, rebuild docker images and do docker-compose up?

**Comment by xcompass** [comment]
You should be able to rebuild the docker image and run it. The image will take care of the upgrade. Though I would make sure data is backed up and possibly do a snapshot on the VM in case there is something wrong with the upgrade.

**Comment by ismarslomic** [comment]
Thanks @xcompass!

Here are the steps i performed:
1. Stop mattermost docker container
2. Backup complete folder (mattermost-docker), even I only had changes in `volumes` folder and `docker-compose.yml` file
3. Run `git pull`
4. Run `docker-compose build`
5. Run `docker-compose up -d`

Would it be possible to extend README with these details. I assume more people might be interested?
